// Code generated by teleiq-gen. DO NOT EDIT.

package teleiq

import (
	"context"
	"encoding/json"

	"github.com/DhurghamAhmed/teleiq/models"
)

// Use this method to receive incoming updates using long polling (wiki).
func (c *Client) GetUpdates(ctx context.Context, params GetUpdatesParams) ([]models.Update, error) {
	var result []models.Update
	if err := c.Call(ctx, "getUpdates", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to specify a URL and receive incoming updates via an outgoing webhook.
func (c *Client) SetWebhook(ctx context.Context, params SetWebhookParams) error {
	return c.Call(ctx, "setWebhook", params, nil)
}

// Use this method to remove webhook integration if you decide to switch back to getUpdates.
func (c *Client) DeleteWebhook(ctx context.Context, params DeleteWebhookParams) error {
	return c.Call(ctx, "deleteWebhook", params, nil)
}

// Use this method to get current webhook status.
func (c *Client) GetWebhookInfo(ctx context.Context) (*models.WebhookInfo, error) {
	var result models.WebhookInfo
	if err := c.Call(ctx, "getWebhookInfo", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// A simple method for testing your bot's authentication token.
func (c *Client) GetMe(ctx context.Context) (*models.User, error) {
	var result models.User
	if err := c.Call(ctx, "getMe", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to log out from the cloud Bot API server before launching the bot locally.
func (c *Client) LogOut(ctx context.Context) error {
	return c.Call(ctx, "logOut", nil, nil)
}

// Use this method to close the bot instance before moving it from one local server to another.
func (c *Client) Close(ctx context.Context) error {
	return c.Call(ctx, "close", nil, nil)
}

// Use this method to send text messages.
func (c *Client) SendMessage(ctx context.Context, params SendMessageParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to forward messages of any kind.
func (c *Client) ForwardMessage(ctx context.Context, params ForwardMessageParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "forwardMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to forward multiple messages of any kind.
func (c *Client) ForwardMessages(ctx context.Context, params ForwardMessagesParams) ([]models.MessageId, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result []models.MessageId
	if err := c.Call(ctx, "forwardMessages", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to copy messages of any kind.
func (c *Client) CopyMessage(ctx context.Context, params CopyMessageParams) (*models.MessageId, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.MessageId
	if err := c.Call(ctx, "copyMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to copy messages of any kind.
func (c *Client) CopyMessages(ctx context.Context, params CopyMessagesParams) ([]models.MessageId, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result []models.MessageId
	if err := c.Call(ctx, "copyMessages", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to send photos.
func (c *Client) SendPhoto(ctx context.Context, params SendPhotoParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendPhoto", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send live photos.
func (c *Client) SendLivePhoto(ctx context.Context, params SendLivePhotoParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendLivePhoto", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send audio files, if you want Telegram clients to display them in the music
// player.
func (c *Client) SendAudio(ctx context.Context, params SendAudioParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendAudio", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send general files.
func (c *Client) SendDocument(ctx context.Context, params SendDocumentParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendDocument", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send video files, Telegram clients support MPEG4 videos (other formats may be
// sent as Document).
func (c *Client) SendVideo(ctx context.Context, params SendVideoParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendVideo", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send animation files (GIF or H.264/MPEG-4 AVC video without sound).
func (c *Client) SendAnimation(ctx context.Context, params SendAnimationParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendAnimation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send audio files, if you want Telegram clients to display the file as a
// playable voice message.
func (c *Client) SendVoice(ctx context.Context, params SendVoiceParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendVoice", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send a rounded square MPEG4 video of up to 1 minute long.
func (c *Client) SendVideoNote(ctx context.Context, params SendVideoNoteParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendVideoNote", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send paid media.
func (c *Client) SendPaidMedia(ctx context.Context, params SendPaidMediaParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendPaidMedia", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send a group of photos, live photos, videos, documents or audios as an album.
func (c *Client) SendMediaGroup(ctx context.Context, params SendMediaGroupParams) ([]models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result []models.Message
	if err := c.Call(ctx, "sendMediaGroup", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to send point on the map.
func (c *Client) SendLocation(ctx context.Context, params SendLocationParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendLocation", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send information about a venue.
func (c *Client) SendVenue(ctx context.Context, params SendVenueParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendVenue", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send phone contacts.
func (c *Client) SendContact(ctx context.Context, params SendContactParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendContact", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send a native poll.
func (c *Client) SendPoll(ctx context.Context, params SendPollParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendPoll", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send a checklist on behalf of a connected business account.
func (c *Client) SendChecklist(ctx context.Context, params SendChecklistParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendChecklist", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to send an animated emoji that will display a random value.
func (c *Client) SendDice(ctx context.Context, params SendDiceParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendDice", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to stream a partial message to a user while the message is being generated.
func (c *Client) SendMessageDraft(ctx context.Context, params SendMessageDraftParams) error {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	return c.Call(ctx, "sendMessageDraft", params, nil)
}

// Use this method when you need to tell the user that something is happening on the bot's side.
func (c *Client) SendChatAction(ctx context.Context, params SendChatActionParams) error {
	return c.Call(ctx, "sendChatAction", params, nil)
}

// Use this method to change the chosen reactions on a message.
func (c *Client) SetMessageReaction(ctx context.Context, params SetMessageReactionParams) error {
	return c.Call(ctx, "setMessageReaction", params, nil)
}

// Use this method to get a list of profile pictures for a user.
func (c *Client) GetUserProfilePhotos(ctx context.Context, params GetUserProfilePhotosParams) (*models.UserProfilePhotos, error) {
	var result models.UserProfilePhotos
	if err := c.Call(ctx, "getUserProfilePhotos", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get a list of profile audios for a user.
func (c *Client) GetUserProfileAudios(ctx context.Context, params GetUserProfileAudiosParams) (*models.UserProfileAudios, error) {
	var result models.UserProfileAudios
	if err := c.Call(ctx, "getUserProfileAudios", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Changes the emoji status for a given user that previously allowed the bot to manage their emoji
// status via the Mini App method requestEmojiStatusAccess.
func (c *Client) SetUserEmojiStatus(ctx context.Context, params SetUserEmojiStatusParams) error {
	return c.Call(ctx, "setUserEmojiStatus", params, nil)
}

// Use this method to get basic information about a file and prepare it for downloading.
func (c *Client) GetFile(ctx context.Context, params GetFileParams) (*models.File, error) {
	var result models.File
	if err := c.Call(ctx, "getFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to ban a user in a group, a supergroup or a channel.
func (c *Client) BanChatMember(ctx context.Context, params BanChatMemberParams) error {
	return c.Call(ctx, "banChatMember", params, nil)
}

// Use this method to unban a previously banned user in a supergroup or channel.
func (c *Client) UnbanChatMember(ctx context.Context, params UnbanChatMemberParams) error {
	return c.Call(ctx, "unbanChatMember", params, nil)
}

// Use this method to restrict a user in a supergroup.
func (c *Client) RestrictChatMember(ctx context.Context, params RestrictChatMemberParams) error {
	return c.Call(ctx, "restrictChatMember", params, nil)
}

// Use this method to promote or demote a user in a supergroup or a channel.
func (c *Client) PromoteChatMember(ctx context.Context, params PromoteChatMemberParams) error {
	return c.Call(ctx, "promoteChatMember", params, nil)
}

// Use this method to set a custom title for an administrator in a supergroup promoted by the bot.
func (c *Client) SetChatAdministratorCustomTitle(ctx context.Context, params SetChatAdministratorCustomTitleParams) error {
	return c.Call(ctx, "setChatAdministratorCustomTitle", params, nil)
}

// Use this method to set a tag for a regular member in a group or a supergroup.
func (c *Client) SetChatMemberTag(ctx context.Context, params SetChatMemberTagParams) error {
	return c.Call(ctx, "setChatMemberTag", params, nil)
}

// Use this method to ban a channel chat in a supergroup or a channel.
func (c *Client) BanChatSenderChat(ctx context.Context, params BanChatSenderChatParams) error {
	return c.Call(ctx, "banChatSenderChat", params, nil)
}

// Use this method to unban a previously banned channel chat in a supergroup or channel.
func (c *Client) UnbanChatSenderChat(ctx context.Context, params UnbanChatSenderChatParams) error {
	return c.Call(ctx, "unbanChatSenderChat", params, nil)
}

// Use this method to set default chat permissions for all members.
func (c *Client) SetChatPermissions(ctx context.Context, params SetChatPermissionsParams) error {
	return c.Call(ctx, "setChatPermissions", params, nil)
}

// Use this method to generate a new primary invite link for a chat; any previously generated
// primary link is revoked.
func (c *Client) ExportChatInviteLink(ctx context.Context, params ExportChatInviteLinkParams) (string, error) {
	var result string
	if err := c.Call(ctx, "exportChatInviteLink", params, &result); err != nil {
		return "", err
	}
	return result, nil
}

// Use this method to create an additional invite link for a chat.
func (c *Client) CreateChatInviteLink(ctx context.Context, params CreateChatInviteLinkParams) (*models.ChatInviteLink, error) {
	var result models.ChatInviteLink
	if err := c.Call(ctx, "createChatInviteLink", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit a non-primary invite link created by the bot.
func (c *Client) EditChatInviteLink(ctx context.Context, params EditChatInviteLinkParams) (*models.ChatInviteLink, error) {
	var result models.ChatInviteLink
	if err := c.Call(ctx, "editChatInviteLink", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to create a subscription invite link for a channel chat.
func (c *Client) CreateChatSubscriptionInviteLink(ctx context.Context, params CreateChatSubscriptionInviteLinkParams) (*models.ChatInviteLink, error) {
	var result models.ChatInviteLink
	if err := c.Call(ctx, "createChatSubscriptionInviteLink", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit a subscription invite link created by the bot.
func (c *Client) EditChatSubscriptionInviteLink(ctx context.Context, params EditChatSubscriptionInviteLinkParams) (*models.ChatInviteLink, error) {
	var result models.ChatInviteLink
	if err := c.Call(ctx, "editChatSubscriptionInviteLink", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to revoke an invite link created by the bot.
func (c *Client) RevokeChatInviteLink(ctx context.Context, params RevokeChatInviteLinkParams) (*models.ChatInviteLink, error) {
	var result models.ChatInviteLink
	if err := c.Call(ctx, "revokeChatInviteLink", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to approve a chat join request.
func (c *Client) ApproveChatJoinRequest(ctx context.Context, params ApproveChatJoinRequestParams) error {
	return c.Call(ctx, "approveChatJoinRequest", params, nil)
}

// Use this method to decline a chat join request.
func (c *Client) DeclineChatJoinRequest(ctx context.Context, params DeclineChatJoinRequestParams) error {
	return c.Call(ctx, "declineChatJoinRequest", params, nil)
}

// Use this method to process a received chat join request query.
func (c *Client) AnswerChatJoinRequestQuery(ctx context.Context, params AnswerChatJoinRequestQueryParams) error {
	return c.Call(ctx, "answerChatJoinRequestQuery", params, nil)
}

// Use this method to process a received chat join request query by showing a Mini App to the user
// before deciding the outcome.
func (c *Client) SendChatJoinRequestWebApp(ctx context.Context, params SendChatJoinRequestWebAppParams) error {
	return c.Call(ctx, "sendChatJoinRequestWebApp", params, nil)
}

// Use this method to set a new profile photo for the chat.
func (c *Client) SetChatPhoto(ctx context.Context, params SetChatPhotoParams) error {
	return c.Call(ctx, "setChatPhoto", params, nil)
}

// Use this method to delete a chat photo.
func (c *Client) DeleteChatPhoto(ctx context.Context, params DeleteChatPhotoParams) error {
	return c.Call(ctx, "deleteChatPhoto", params, nil)
}

// Use this method to change the title of a chat.
func (c *Client) SetChatTitle(ctx context.Context, params SetChatTitleParams) error {
	return c.Call(ctx, "setChatTitle", params, nil)
}

// Use this method to change the description of a group, a supergroup or a channel.
func (c *Client) SetChatDescription(ctx context.Context, params SetChatDescriptionParams) error {
	return c.Call(ctx, "setChatDescription", params, nil)
}

// Use this method to add a message to the list of pinned messages in a chat.
func (c *Client) PinChatMessage(ctx context.Context, params PinChatMessageParams) error {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	return c.Call(ctx, "pinChatMessage", params, nil)
}

// Use this method to remove a message from the list of pinned messages in a chat.
func (c *Client) UnpinChatMessage(ctx context.Context, params UnpinChatMessageParams) error {
	return c.Call(ctx, "unpinChatMessage", params, nil)
}

// Use this method to clear the list of pinned messages in a chat.
func (c *Client) UnpinAllChatMessages(ctx context.Context, params UnpinAllChatMessagesParams) error {
	return c.Call(ctx, "unpinAllChatMessages", params, nil)
}

// Use this method for your bot to leave a group, supergroup or channel.
func (c *Client) LeaveChat(ctx context.Context, params LeaveChatParams) error {
	return c.Call(ctx, "leaveChat", params, nil)
}

// Use this method to get up-to-date information about the chat.
func (c *Client) GetChat(ctx context.Context, params GetChatParams) (*models.ChatFullInfo, error) {
	var result models.ChatFullInfo
	if err := c.Call(ctx, "getChat", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get a list of administrators in a chat.
func (c *Client) GetChatAdministrators(ctx context.Context, params GetChatAdministratorsParams) ([]models.ChatMember, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "getChatAdministrators", params, &raw); err != nil {
		return nil, err
	}
	return decodeUnions("getChatAdministrators", raw, models.DecodeChatMember)
}

// Use this method to get the number of members in a chat.
func (c *Client) GetChatMemberCount(ctx context.Context, params GetChatMemberCountParams) (int, error) {
	var result int
	if err := c.Call(ctx, "getChatMemberCount", params, &result); err != nil {
		return 0, err
	}
	return result, nil
}

// Use this method to get information about a member of a chat.
func (c *Client) GetChatMember(ctx context.Context, params GetChatMemberParams) (models.ChatMember, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "getChatMember", params, &raw); err != nil {
		return nil, err
	}
	return decodeUnion("getChatMember", raw, models.DecodeChatMember)
}

// Use this method to get the last messages from the personal chat (i.e., the chat currently added
// to their profile) of a given user.
func (c *Client) GetUserPersonalChatMessages(ctx context.Context, params GetUserPersonalChatMessagesParams) ([]models.Message, error) {
	var result []models.Message
	if err := c.Call(ctx, "getUserPersonalChatMessages", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to set a new group sticker set for a supergroup.
func (c *Client) SetChatStickerSet(ctx context.Context, params SetChatStickerSetParams) error {
	return c.Call(ctx, "setChatStickerSet", params, nil)
}

// Use this method to delete a group sticker set from a supergroup.
func (c *Client) DeleteChatStickerSet(ctx context.Context, params DeleteChatStickerSetParams) error {
	return c.Call(ctx, "deleteChatStickerSet", params, nil)
}

// Use this method to get custom emoji stickers, which can be used as a forum topic icon by any
// user.
func (c *Client) GetForumTopicIconStickers(ctx context.Context) ([]models.Sticker, error) {
	var result []models.Sticker
	if err := c.Call(ctx, "getForumTopicIconStickers", nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to create a topic in a forum supergroup chat or a private chat with a user.
func (c *Client) CreateForumTopic(ctx context.Context, params CreateForumTopicParams) (*models.ForumTopic, error) {
	var result models.ForumTopic
	if err := c.Call(ctx, "createForumTopic", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit name and icon of a topic in a forum supergroup chat or a private chat
// with a user.
func (c *Client) EditForumTopic(ctx context.Context, params EditForumTopicParams) error {
	return c.Call(ctx, "editForumTopic", params, nil)
}

// Use this method to close an open topic in a forum supergroup chat.
func (c *Client) CloseForumTopic(ctx context.Context, params CloseForumTopicParams) error {
	return c.Call(ctx, "closeForumTopic", params, nil)
}

// Use this method to reopen a closed topic in a forum supergroup chat.
func (c *Client) ReopenForumTopic(ctx context.Context, params ReopenForumTopicParams) error {
	return c.Call(ctx, "reopenForumTopic", params, nil)
}

// Use this method to delete a forum topic along with all its messages in a forum supergroup chat or
// a private chat with a user.
func (c *Client) DeleteForumTopic(ctx context.Context, params DeleteForumTopicParams) error {
	return c.Call(ctx, "deleteForumTopic", params, nil)
}

// Use this method to clear the list of pinned messages in a forum topic in a forum supergroup chat
// or a private chat with a user.
func (c *Client) UnpinAllForumTopicMessages(ctx context.Context, params UnpinAllForumTopicMessagesParams) error {
	return c.Call(ctx, "unpinAllForumTopicMessages", params, nil)
}

// Use this method to edit the name of the 'General' topic in a forum supergroup chat.
func (c *Client) EditGeneralForumTopic(ctx context.Context, params EditGeneralForumTopicParams) error {
	return c.Call(ctx, "editGeneralForumTopic", params, nil)
}

// Use this method to close an open 'General' topic in a forum supergroup chat.
func (c *Client) CloseGeneralForumTopic(ctx context.Context, params CloseGeneralForumTopicParams) error {
	return c.Call(ctx, "closeGeneralForumTopic", params, nil)
}

// Use this method to reopen a closed 'General' topic in a forum supergroup chat.
func (c *Client) ReopenGeneralForumTopic(ctx context.Context, params ReopenGeneralForumTopicParams) error {
	return c.Call(ctx, "reopenGeneralForumTopic", params, nil)
}

// Use this method to hide the 'General' topic in a forum supergroup chat.
func (c *Client) HideGeneralForumTopic(ctx context.Context, params HideGeneralForumTopicParams) error {
	return c.Call(ctx, "hideGeneralForumTopic", params, nil)
}

// Use this method to unhide the 'General' topic in a forum supergroup chat.
func (c *Client) UnhideGeneralForumTopic(ctx context.Context, params UnhideGeneralForumTopicParams) error {
	return c.Call(ctx, "unhideGeneralForumTopic", params, nil)
}

// Use this method to clear the list of pinned messages in a General forum topic.
func (c *Client) UnpinAllGeneralForumTopicMessages(ctx context.Context, params UnpinAllGeneralForumTopicMessagesParams) error {
	return c.Call(ctx, "unpinAllGeneralForumTopicMessages", params, nil)
}

// Use this method to send answers to callback queries sent from inline keyboards.
func (c *Client) AnswerCallbackQuery(ctx context.Context, params AnswerCallbackQueryParams) error {
	return c.Call(ctx, "answerCallbackQuery", params, nil)
}

// Use this method to reply to a received guest message.
func (c *Client) AnswerGuestQuery(ctx context.Context, params AnswerGuestQueryParams) (*models.SentGuestMessage, error) {
	var result models.SentGuestMessage
	if err := c.Call(ctx, "answerGuestQuery", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get the list of boosts added to a chat by a user.
func (c *Client) GetUserChatBoosts(ctx context.Context, params GetUserChatBoostsParams) (*models.UserChatBoosts, error) {
	var result models.UserChatBoosts
	if err := c.Call(ctx, "getUserChatBoosts", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get information about the connection of the bot with a business account.
func (c *Client) GetBusinessConnection(ctx context.Context, params GetBusinessConnectionParams) (*models.BusinessConnection, error) {
	var result models.BusinessConnection
	if err := c.Call(ctx, "getBusinessConnection", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get the token of a managed bot.
func (c *Client) GetManagedBotToken(ctx context.Context, params GetManagedBotTokenParams) (string, error) {
	var result string
	if err := c.Call(ctx, "getManagedBotToken", params, &result); err != nil {
		return "", err
	}
	return result, nil
}

// Use this method to revoke the current token of a managed bot and generate a new one.
func (c *Client) ReplaceManagedBotToken(ctx context.Context, params ReplaceManagedBotTokenParams) (string, error) {
	var result string
	if err := c.Call(ctx, "replaceManagedBotToken", params, &result); err != nil {
		return "", err
	}
	return result, nil
}

// Use this method to get the access settings of a managed bot.
func (c *Client) GetManagedBotAccessSettings(ctx context.Context, params GetManagedBotAccessSettingsParams) (*models.BotAccessSettings, error) {
	var result models.BotAccessSettings
	if err := c.Call(ctx, "getManagedBotAccessSettings", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to change the access settings of a managed bot.
func (c *Client) SetManagedBotAccessSettings(ctx context.Context, params SetManagedBotAccessSettingsParams) error {
	return c.Call(ctx, "setManagedBotAccessSettings", params, nil)
}

// Use this method to change the list of the bot's commands.
func (c *Client) SetMyCommands(ctx context.Context, params SetMyCommandsParams) error {
	return c.Call(ctx, "setMyCommands", params, nil)
}

// Use this method to delete the list of the bot's commands for the given scope and user language.
func (c *Client) DeleteMyCommands(ctx context.Context, params DeleteMyCommandsParams) error {
	return c.Call(ctx, "deleteMyCommands", params, nil)
}

// Use this method to get the current list of the bot's commands for the given scope and user
// language.
func (c *Client) GetMyCommands(ctx context.Context, params GetMyCommandsParams) ([]models.BotCommand, error) {
	var result []models.BotCommand
	if err := c.Call(ctx, "getMyCommands", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to change the bot's name.
func (c *Client) SetMyName(ctx context.Context, params SetMyNameParams) error {
	return c.Call(ctx, "setMyName", params, nil)
}

// Use this method to get the current bot name for the given user language.
func (c *Client) GetMyName(ctx context.Context, params GetMyNameParams) (*models.BotName, error) {
	var result models.BotName
	if err := c.Call(ctx, "getMyName", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to change the bot's description, which is shown in the chat with the bot if the
// chat is empty.
func (c *Client) SetMyDescription(ctx context.Context, params SetMyDescriptionParams) error {
	return c.Call(ctx, "setMyDescription", params, nil)
}

// Use this method to get the current bot description for the given user language.
func (c *Client) GetMyDescription(ctx context.Context, params GetMyDescriptionParams) (*models.BotDescription, error) {
	var result models.BotDescription
	if err := c.Call(ctx, "getMyDescription", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to change the bot's short description, which is shown on the bot's profile page
// and is sent together with the link when users share the bot.
func (c *Client) SetMyShortDescription(ctx context.Context, params SetMyShortDescriptionParams) error {
	return c.Call(ctx, "setMyShortDescription", params, nil)
}

// Use this method to get the current bot short description for the given user language.
func (c *Client) GetMyShortDescription(ctx context.Context, params GetMyShortDescriptionParams) (*models.BotShortDescription, error) {
	var result models.BotShortDescription
	if err := c.Call(ctx, "getMyShortDescription", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Changes the profile photo of the bot.
func (c *Client) SetMyProfilePhoto(ctx context.Context, params SetMyProfilePhotoParams) error {
	return c.Call(ctx, "setMyProfilePhoto", params, nil)
}

// Removes the profile photo of the bot.
func (c *Client) RemoveMyProfilePhoto(ctx context.Context) error {
	return c.Call(ctx, "removeMyProfilePhoto", nil, nil)
}

// Use this method to change the bot's menu button in a private chat, or the default menu button.
func (c *Client) SetChatMenuButton(ctx context.Context, params SetChatMenuButtonParams) error {
	return c.Call(ctx, "setChatMenuButton", params, nil)
}

// Use this method to get the current value of the bot's menu button in a private chat, or the
// default menu button.
func (c *Client) GetChatMenuButton(ctx context.Context, params GetChatMenuButtonParams) (models.MenuButton, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "getChatMenuButton", params, &raw); err != nil {
		return nil, err
	}
	return decodeUnion("getChatMenuButton", raw, models.DecodeMenuButton)
}

// Use this method to change the default administrator rights requested by the bot when it's added
// as an administrator to groups or channels.
func (c *Client) SetMyDefaultAdministratorRights(ctx context.Context, params SetMyDefaultAdministratorRightsParams) error {
	return c.Call(ctx, "setMyDefaultAdministratorRights", params, nil)
}

// Use this method to get the current default administrator rights of the bot.
func (c *Client) GetMyDefaultAdministratorRights(ctx context.Context, params GetMyDefaultAdministratorRightsParams) (*models.ChatAdministratorRights, error) {
	var result models.ChatAdministratorRights
	if err := c.Call(ctx, "getMyDefaultAdministratorRights", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Returns the list of gifts that can be sent by the bot to users and channel chats.
func (c *Client) GetAvailableGifts(ctx context.Context) (*models.Gifts, error) {
	var result models.Gifts
	if err := c.Call(ctx, "getAvailableGifts", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Sends a gift to the given user or channel chat.
func (c *Client) SendGift(ctx context.Context, params SendGiftParams) error {
	return c.Call(ctx, "sendGift", params, nil)
}

// Gifts a Telegram Premium subscription to the given user.
func (c *Client) GiftPremiumSubscription(ctx context.Context, params GiftPremiumSubscriptionParams) error {
	return c.Call(ctx, "giftPremiumSubscription", params, nil)
}

// Verifies a user on behalf of the organization which is represented by the bot.
func (c *Client) VerifyUser(ctx context.Context, params VerifyUserParams) error {
	return c.Call(ctx, "verifyUser", params, nil)
}

// Verifies a chat on behalf of the organization which is represented by the bot.
func (c *Client) VerifyChat(ctx context.Context, params VerifyChatParams) error {
	return c.Call(ctx, "verifyChat", params, nil)
}

// Removes verification from a user who is currently verified on behalf of the organization
// represented by the bot.
func (c *Client) RemoveUserVerification(ctx context.Context, params RemoveUserVerificationParams) error {
	return c.Call(ctx, "removeUserVerification", params, nil)
}

// Removes verification from a chat that is currently verified on behalf of the organization
// represented by the bot.
func (c *Client) RemoveChatVerification(ctx context.Context, params RemoveChatVerificationParams) error {
	return c.Call(ctx, "removeChatVerification", params, nil)
}

// Marks incoming message as read on behalf of a business account.
func (c *Client) ReadBusinessMessage(ctx context.Context, params ReadBusinessMessageParams) error {
	return c.Call(ctx, "readBusinessMessage", params, nil)
}

// Delete messages on behalf of a business account.
func (c *Client) DeleteBusinessMessages(ctx context.Context, params DeleteBusinessMessagesParams) error {
	return c.Call(ctx, "deleteBusinessMessages", params, nil)
}

// Changes the first and last name of a managed business account.
func (c *Client) SetBusinessAccountName(ctx context.Context, params SetBusinessAccountNameParams) error {
	return c.Call(ctx, "setBusinessAccountName", params, nil)
}

// Changes the username of a managed business account.
func (c *Client) SetBusinessAccountUsername(ctx context.Context, params SetBusinessAccountUsernameParams) error {
	return c.Call(ctx, "setBusinessAccountUsername", params, nil)
}

// Changes the bio of a managed business account.
func (c *Client) SetBusinessAccountBio(ctx context.Context, params SetBusinessAccountBioParams) error {
	return c.Call(ctx, "setBusinessAccountBio", params, nil)
}

// Changes the profile photo of a managed business account.
func (c *Client) SetBusinessAccountProfilePhoto(ctx context.Context, params SetBusinessAccountProfilePhotoParams) error {
	return c.Call(ctx, "setBusinessAccountProfilePhoto", params, nil)
}

// Removes the current profile photo of a managed business account.
func (c *Client) RemoveBusinessAccountProfilePhoto(ctx context.Context, params RemoveBusinessAccountProfilePhotoParams) error {
	return c.Call(ctx, "removeBusinessAccountProfilePhoto", params, nil)
}

// Changes the privacy settings pertaining to incoming gifts in a managed business account.
func (c *Client) SetBusinessAccountGiftSettings(ctx context.Context, params SetBusinessAccountGiftSettingsParams) error {
	return c.Call(ctx, "setBusinessAccountGiftSettings", params, nil)
}

// Returns the amount of Telegram Stars owned by a managed business account.
func (c *Client) GetBusinessAccountStarBalance(ctx context.Context, params GetBusinessAccountStarBalanceParams) (*models.StarAmount, error) {
	var result models.StarAmount
	if err := c.Call(ctx, "getBusinessAccountStarBalance", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Transfers Telegram Stars from the business account balance to the bot's balance.
func (c *Client) TransferBusinessAccountStars(ctx context.Context, params TransferBusinessAccountStarsParams) error {
	return c.Call(ctx, "transferBusinessAccountStars", params, nil)
}

// Returns the gifts received and owned by a managed business account.
func (c *Client) GetBusinessAccountGifts(ctx context.Context, params GetBusinessAccountGiftsParams) (*models.OwnedGifts, error) {
	var result models.OwnedGifts
	if err := c.Call(ctx, "getBusinessAccountGifts", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Returns the gifts owned and hosted by a user.
func (c *Client) GetUserGifts(ctx context.Context, params GetUserGiftsParams) (*models.OwnedGifts, error) {
	var result models.OwnedGifts
	if err := c.Call(ctx, "getUserGifts", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Returns the gifts owned by a chat.
func (c *Client) GetChatGifts(ctx context.Context, params GetChatGiftsParams) (*models.OwnedGifts, error) {
	var result models.OwnedGifts
	if err := c.Call(ctx, "getChatGifts", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Converts a given regular gift to Telegram Stars.
func (c *Client) ConvertGiftToStars(ctx context.Context, params ConvertGiftToStarsParams) error {
	return c.Call(ctx, "convertGiftToStars", params, nil)
}

// Upgrades a given regular gift to a unique gift.
func (c *Client) UpgradeGift(ctx context.Context, params UpgradeGiftParams) error {
	return c.Call(ctx, "upgradeGift", params, nil)
}

// Transfers an owned unique gift to another user.
func (c *Client) TransferGift(ctx context.Context, params TransferGiftParams) error {
	return c.Call(ctx, "transferGift", params, nil)
}

// Posts a story on behalf of a managed business account.
func (c *Client) PostStory(ctx context.Context, params PostStoryParams) (*models.Story, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Story
	if err := c.Call(ctx, "postStory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Reposts a story on behalf of a business account from another business account.
func (c *Client) RepostStory(ctx context.Context, params RepostStoryParams) (*models.Story, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Story
	if err := c.Call(ctx, "repostStory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edits a story previously posted by the bot on behalf of a managed business account.
func (c *Client) EditStory(ctx context.Context, params EditStoryParams) (*models.Story, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Story
	if err := c.Call(ctx, "editStory", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Deletes a story previously posted by the bot on behalf of a managed business account.
func (c *Client) DeleteStory(ctx context.Context, params DeleteStoryParams) error {
	return c.Call(ctx, "deleteStory", params, nil)
}

// Use this method to set the result of an interaction with a Web App and send a corresponding
// message on behalf of the user to the chat from which the query originated.
func (c *Client) AnswerWebAppQuery(ctx context.Context, params AnswerWebAppQueryParams) (*models.SentWebAppMessage, error) {
	var result models.SentWebAppMessage
	if err := c.Call(ctx, "answerWebAppQuery", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stores a message that can be sent by a user of a Mini App.
func (c *Client) SavePreparedInlineMessage(ctx context.Context, params SavePreparedInlineMessageParams) (*models.PreparedInlineMessage, error) {
	var result models.PreparedInlineMessage
	if err := c.Call(ctx, "savePreparedInlineMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stores a keyboard button that can be used by a user within a Mini App.
func (c *Client) SavePreparedKeyboardButton(ctx context.Context, params SavePreparedKeyboardButtonParams) (*models.PreparedKeyboardButton, error) {
	var result models.PreparedKeyboardButton
	if err := c.Call(ctx, "savePreparedKeyboardButton", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit text, rich and game messages. The Message is nil when the Bot API returns
// True, as it does for inline messages.
func (c *Client) EditMessageText(ctx context.Context, params EditMessageTextParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var raw json.RawMessage
	if err := c.Call(ctx, "editMessageText", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("editMessageText", raw)
}

// Use this method to edit captions of messages. The Message is nil when the Bot API returns True,
// as it does for inline messages.
func (c *Client) EditMessageCaption(ctx context.Context, params EditMessageCaptionParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var raw json.RawMessage
	if err := c.Call(ctx, "editMessageCaption", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("editMessageCaption", raw)
}

// Use this method to edit animation, audio, document, live photo, photo, or video messages, or to
// replace a text or a rich message with a media. The Message is nil when the Bot API returns True,
// as it does for inline messages.
func (c *Client) EditMessageMedia(ctx context.Context, params EditMessageMediaParams) (*models.Message, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "editMessageMedia", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("editMessageMedia", raw)
}

// Use this method to edit live location messages. The Message is nil when the Bot API returns True,
// as it does for inline messages.
func (c *Client) EditMessageLiveLocation(ctx context.Context, params EditMessageLiveLocationParams) (*models.Message, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "editMessageLiveLocation", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("editMessageLiveLocation", raw)
}

// Use this method to stop updating a live location message before live_period expires. The Message
// is nil when the Bot API returns True, as it does for inline messages.
func (c *Client) StopMessageLiveLocation(ctx context.Context, params StopMessageLiveLocationParams) (*models.Message, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "stopMessageLiveLocation", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("stopMessageLiveLocation", raw)
}

// Use this method to edit a checklist on behalf of a connected business account.
func (c *Client) EditMessageChecklist(ctx context.Context, params EditMessageChecklistParams) (*models.Message, error) {
	var result models.Message
	if err := c.Call(ctx, "editMessageChecklist", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit only the reply markup of messages. The Message is nil when the Bot API
// returns True, as it does for inline messages.
func (c *Client) EditMessageReplyMarkup(ctx context.Context, params EditMessageReplyMarkupParams) (*models.Message, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "editMessageReplyMarkup", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("editMessageReplyMarkup", raw)
}

// Use this method to stop a poll which was sent by the bot.
func (c *Client) StopPoll(ctx context.Context, params StopPollParams) (*models.Poll, error) {
	var result models.Poll
	if err := c.Call(ctx, "stopPoll", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to edit an ephemeral text or rich message.
func (c *Client) EditEphemeralMessageText(ctx context.Context, params EditEphemeralMessageTextParams) error {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	return c.Call(ctx, "editEphemeralMessageText", params, nil)
}

// Use this method to edit the media of an ephemeral message.
func (c *Client) EditEphemeralMessageMedia(ctx context.Context, params EditEphemeralMessageMediaParams) error {
	return c.Call(ctx, "editEphemeralMessageMedia", params, nil)
}

// Use this method to edit the caption of an ephemeral message.
func (c *Client) EditEphemeralMessageCaption(ctx context.Context, params EditEphemeralMessageCaptionParams) error {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	return c.Call(ctx, "editEphemeralMessageCaption", params, nil)
}

// Use this method to edit only the reply markup of an ephemeral message.
func (c *Client) EditEphemeralMessageReplyMarkup(ctx context.Context, params EditEphemeralMessageReplyMarkupParams) error {
	return c.Call(ctx, "editEphemeralMessageReplyMarkup", params, nil)
}

// Use this method to approve a suggested post in a direct messages chat.
func (c *Client) ApproveSuggestedPost(ctx context.Context, params ApproveSuggestedPostParams) error {
	return c.Call(ctx, "approveSuggestedPost", params, nil)
}

// Use this method to decline a suggested post in a direct messages chat.
func (c *Client) DeclineSuggestedPost(ctx context.Context, params DeclineSuggestedPostParams) error {
	return c.Call(ctx, "declineSuggestedPost", params, nil)
}

// Use this method to delete a message, including service messages, with the following limitations:
// - A message can only be deleted if it was sent less than 48 hours ago.
func (c *Client) DeleteMessage(ctx context.Context, params DeleteMessageParams) error {
	return c.Call(ctx, "deleteMessage", params, nil)
}

// Use this method to delete multiple messages simultaneously.
func (c *Client) DeleteMessages(ctx context.Context, params DeleteMessagesParams) error {
	return c.Call(ctx, "deleteMessages", params, nil)
}

// Use this method to delete an ephemeral message.
func (c *Client) DeleteEphemeralMessage(ctx context.Context, params DeleteEphemeralMessageParams) error {
	return c.Call(ctx, "deleteEphemeralMessage", params, nil)
}

// Use this method to remove a reaction from a message in a group or a supergroup chat.
func (c *Client) DeleteMessageReaction(ctx context.Context, params DeleteMessageReactionParams) error {
	return c.Call(ctx, "deleteMessageReaction", params, nil)
}

// Use this method to remove up to 10000 recent reactions in a group or a supergroup chat added by a
// given user or chat.
func (c *Client) DeleteAllMessageReactions(ctx context.Context, params DeleteAllMessageReactionsParams) error {
	return c.Call(ctx, "deleteAllMessageReactions", params, nil)
}

// Use this method to send static .WEBP, animated .TGS, or video .WEBM stickers.
func (c *Client) SendSticker(ctx context.Context, params SendStickerParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendSticker", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get a sticker set.
func (c *Client) GetStickerSet(ctx context.Context, params GetStickerSetParams) (*models.StickerSet, error) {
	var result models.StickerSet
	if err := c.Call(ctx, "getStickerSet", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to get information about custom emoji stickers by their identifiers.
func (c *Client) GetCustomEmojiStickers(ctx context.Context, params GetCustomEmojiStickersParams) ([]models.Sticker, error) {
	var result []models.Sticker
	if err := c.Call(ctx, "getCustomEmojiStickers", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// Use this method to upload a file with a sticker for later use in the createNewStickerSet,
// addStickerToSet, or replaceStickerInSet methods (the file can be used multiple times).
func (c *Client) UploadStickerFile(ctx context.Context, params UploadStickerFileParams) (*models.File, error) {
	var result models.File
	if err := c.Call(ctx, "uploadStickerFile", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to create a new sticker set owned by a user.
func (c *Client) CreateNewStickerSet(ctx context.Context, params CreateNewStickerSetParams) error {
	return c.Call(ctx, "createNewStickerSet", params, nil)
}

// Use this method to add a new sticker to a set created by the bot.
func (c *Client) AddStickerToSet(ctx context.Context, params AddStickerToSetParams) error {
	return c.Call(ctx, "addStickerToSet", params, nil)
}

// Use this method to move a sticker in a set created by the bot to a specific position.
func (c *Client) SetStickerPositionInSet(ctx context.Context, params SetStickerPositionInSetParams) error {
	return c.Call(ctx, "setStickerPositionInSet", params, nil)
}

// Use this method to delete a sticker from a set created by the bot.
func (c *Client) DeleteStickerFromSet(ctx context.Context, params DeleteStickerFromSetParams) error {
	return c.Call(ctx, "deleteStickerFromSet", params, nil)
}

// Use this method to replace an existing sticker in a sticker set with a new one.
func (c *Client) ReplaceStickerInSet(ctx context.Context, params ReplaceStickerInSetParams) error {
	return c.Call(ctx, "replaceStickerInSet", params, nil)
}

// Use this method to change the list of emoji assigned to a regular or custom emoji sticker.
func (c *Client) SetStickerEmojiList(ctx context.Context, params SetStickerEmojiListParams) error {
	return c.Call(ctx, "setStickerEmojiList", params, nil)
}

// Use this method to change search keywords assigned to a regular or custom emoji sticker.
func (c *Client) SetStickerKeywords(ctx context.Context, params SetStickerKeywordsParams) error {
	return c.Call(ctx, "setStickerKeywords", params, nil)
}

// Use this method to change the mask position of a mask sticker.
func (c *Client) SetStickerMaskPosition(ctx context.Context, params SetStickerMaskPositionParams) error {
	return c.Call(ctx, "setStickerMaskPosition", params, nil)
}

// Use this method to set the title of a created sticker set.
func (c *Client) SetStickerSetTitle(ctx context.Context, params SetStickerSetTitleParams) error {
	return c.Call(ctx, "setStickerSetTitle", params, nil)
}

// Use this method to set the thumbnail of a regular or mask sticker set.
func (c *Client) SetStickerSetThumbnail(ctx context.Context, params SetStickerSetThumbnailParams) error {
	return c.Call(ctx, "setStickerSetThumbnail", params, nil)
}

// Use this method to set the thumbnail of a custom emoji sticker set.
func (c *Client) SetCustomEmojiStickerSetThumbnail(ctx context.Context, params SetCustomEmojiStickerSetThumbnailParams) error {
	return c.Call(ctx, "setCustomEmojiStickerSetThumbnail", params, nil)
}

// Use this method to delete a sticker set that was created by the bot.
func (c *Client) DeleteStickerSet(ctx context.Context, params DeleteStickerSetParams) error {
	return c.Call(ctx, "deleteStickerSet", params, nil)
}

// Use this method to send rich messages.
func (c *Client) SendRichMessage(ctx context.Context, params SendRichMessageParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendRichMessage", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to stream a partial rich message to a user while the message is being generated.
func (c *Client) SendRichMessageDraft(ctx context.Context, params SendRichMessageDraftParams) error {
	return c.Call(ctx, "sendRichMessageDraft", params, nil)
}

// Use this method to send answers to an inline query.
func (c *Client) AnswerInlineQuery(ctx context.Context, params AnswerInlineQueryParams) error {
	return c.Call(ctx, "answerInlineQuery", params, nil)
}

// Use this method to send invoices.
func (c *Client) SendInvoice(ctx context.Context, params SendInvoiceParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendInvoice", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to create a link for an invoice.
func (c *Client) CreateInvoiceLink(ctx context.Context, params CreateInvoiceLinkParams) (string, error) {
	var result string
	if err := c.Call(ctx, "createInvoiceLink", params, &result); err != nil {
		return "", err
	}
	return result, nil
}

// If you sent an invoice requesting a shipping address and the parameter is_flexible was specified,
// the Bot API will send an Update with a shipping_query field to the bot.
func (c *Client) AnswerShippingQuery(ctx context.Context, params AnswerShippingQueryParams) error {
	return c.Call(ctx, "answerShippingQuery", params, nil)
}

// Once the user has confirmed their payment and shipping details, the Bot API sends the final
// confirmation in the form of an Update with the field pre_checkout_query.
func (c *Client) AnswerPreCheckoutQuery(ctx context.Context, params AnswerPreCheckoutQueryParams) error {
	return c.Call(ctx, "answerPreCheckoutQuery", params, nil)
}

// A method to get the current Telegram Stars balance of the bot.
func (c *Client) GetMyStarBalance(ctx context.Context) (*models.StarAmount, error) {
	var result models.StarAmount
	if err := c.Call(ctx, "getMyStarBalance", nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Returns the bot's Telegram Star transactions in chronological order.
func (c *Client) GetStarTransactions(ctx context.Context, params GetStarTransactionsParams) (*models.StarTransactions, error) {
	var result models.StarTransactions
	if err := c.Call(ctx, "getStarTransactions", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Refunds a successful payment in Telegram Stars.
func (c *Client) RefundStarPayment(ctx context.Context, params RefundStarPaymentParams) error {
	return c.Call(ctx, "refundStarPayment", params, nil)
}

// Allows the bot to cancel or re-enable extension of a subscription paid in Telegram Stars.
func (c *Client) EditUserStarSubscription(ctx context.Context, params EditUserStarSubscriptionParams) error {
	return c.Call(ctx, "editUserStarSubscription", params, nil)
}

// Informs a user that some of the Telegram Passport elements they provided contains errors.
func (c *Client) SetPassportDataErrors(ctx context.Context, params SetPassportDataErrorsParams) error {
	return c.Call(ctx, "setPassportDataErrors", params, nil)
}

// Use this method to send a game.
func (c *Client) SendGame(ctx context.Context, params SendGameParams) (*models.Message, error) {
	if c.defaults != nil {
		params.applyDefaults(c.defaults)
	}
	var result models.Message
	if err := c.Call(ctx, "sendGame", params, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Use this method to set the score of the specified user in a game message. The Message is nil when
// the Bot API returns True, as it does for inline messages.
func (c *Client) SetGameScore(ctx context.Context, params SetGameScoreParams) (*models.Message, error) {
	var raw json.RawMessage
	if err := c.Call(ctx, "setGameScore", params, &raw); err != nil {
		return nil, err
	}
	return decodeOrTrue[models.Message]("setGameScore", raw)
}

// Use this method to get data for high score tables.
func (c *Client) GetGameHighScores(ctx context.Context, params GetGameHighScoresParams) ([]models.GameHighScore, error) {
	var result []models.GameHighScore
	if err := c.Call(ctx, "getGameHighScores", params, &result); err != nil {
		return nil, err
	}
	return result, nil
}
