// Code generated by teleiq-gen. DO NOT EDIT.

package models

// Game represents a game.
type Game struct {
	// Title of the game
	Title string `json:"title"`
	// Description of the game
	Description string `json:"description"`
	// Photo that will be displayed in the game message in chats
	Photo []PhotoSize `json:"photo"`
	// Brief description of the game or high scores included in the game message.
	Text *string `json:"text,omitempty"`
	// Special entities that appear in text, such as usernames, URLs, bot commands, etc.
	TextEntities []MessageEntity `json:"text_entities,omitzero"`
	// Animation that will be displayed in the game message in chats.
	Animation *Animation `json:"animation,omitempty"`
}

// A placeholder, currently holds no information.
type CallbackGame struct{}

// GameHighScore represents one row of the high scores table for a game.
type GameHighScore struct {
	// Position in high score table for the game
	Position int `json:"position"`
	// User
	User User `json:"user"`
	// Score
	Score int `json:"score"`
}
