// Code generated by teleiq-gen. DO NOT EDIT.

package models

import "encoding/json"

// InlineQuery represents an incoming inline query.
type InlineQuery struct {
	// Unique identifier for this query
	ID string `json:"id"`
	// Sender
	From User `json:"from"`
	// Text of the query (up to 256 characters)
	Query string `json:"query"`
	// Offset of the results to be returned, can be controlled by the bot
	Offset string `json:"offset"`
	// Type of the chat from which the inline query was sent.
	ChatType *string `json:"chat_type,omitempty"`
	// Sender location, only for bots that request user location
	Location *Location `json:"location,omitempty"`
}

// InlineQueryResultsButton represents a button to be shown above inline query results.
type InlineQueryResultsButton struct {
	// Label text on the button
	Text string `json:"text"`
	// Description of the Web App that will be launched when the user presses the button.
	WebApp *WebAppInfo `json:"web_app,omitempty"`
	// Deep-linking parameter for the /start message sent to the bot when a user presses the button.
	StartParameter *string `json:"start_parameter,omitempty"`
}

// InlineQueryResult represents one result of an inline query.
//
// Implemented by *InlineQueryResultCachedAudio, *InlineQueryResultCachedDocument,
// *InlineQueryResultCachedGif, *InlineQueryResultCachedMpeg4Gif, *InlineQueryResultCachedPhoto,
// *InlineQueryResultCachedSticker, *InlineQueryResultCachedVideo, *InlineQueryResultCachedVoice,
// *InlineQueryResultArticle, *InlineQueryResultAudio, *InlineQueryResultContact,
// *InlineQueryResultGame, *InlineQueryResultDocument, *InlineQueryResultGif,
// *InlineQueryResultLocation, *InlineQueryResultMpeg4Gif, *InlineQueryResultPhoto,
// *InlineQueryResultVenue, *InlineQueryResultVideo and *InlineQueryResultVoice.
type InlineQueryResult interface{ inlineQueryResult() }

func (*InlineQueryResultCachedAudio) inlineQueryResult()    {}
func (*InlineQueryResultCachedDocument) inlineQueryResult() {}
func (*InlineQueryResultCachedGif) inlineQueryResult()      {}
func (*InlineQueryResultCachedMpeg4Gif) inlineQueryResult() {}
func (*InlineQueryResultCachedPhoto) inlineQueryResult()    {}
func (*InlineQueryResultCachedSticker) inlineQueryResult()  {}
func (*InlineQueryResultCachedVideo) inlineQueryResult()    {}
func (*InlineQueryResultCachedVoice) inlineQueryResult()    {}
func (*InlineQueryResultArticle) inlineQueryResult()        {}
func (*InlineQueryResultAudio) inlineQueryResult()          {}
func (*InlineQueryResultContact) inlineQueryResult()        {}
func (*InlineQueryResultGame) inlineQueryResult()           {}
func (*InlineQueryResultDocument) inlineQueryResult()       {}
func (*InlineQueryResultGif) inlineQueryResult()            {}
func (*InlineQueryResultLocation) inlineQueryResult()       {}
func (*InlineQueryResultMpeg4Gif) inlineQueryResult()       {}
func (*InlineQueryResultPhoto) inlineQueryResult()          {}
func (*InlineQueryResultVenue) inlineQueryResult()          {}
func (*InlineQueryResultVideo) inlineQueryResult()          {}
func (*InlineQueryResultVoice) inlineQueryResult()          {}

// Represents a link to an article or web page.
type InlineQueryResultArticle struct {
	// Unique identifier for this result, 1-64 Bytes
	ID string `json:"id"`
	// Title of the result
	Title string `json:"title"`
	// Content of the message to be sent
	InputMessageContent InputMessageContent `json:"input_message_content"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// URL of the result
	URL *string `json:"url,omitempty"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Url of the thumbnail for the result
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Thumbnail width
	ThumbnailWidth *int `json:"thumbnail_width,omitempty"`
	// Thumbnail height
	ThumbnailHeight *int `json:"thumbnail_height,omitempty"`
}

// MarshalJSON encodes v with "type" set to "article".
func (v InlineQueryResultArticle) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultArticle
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"article", fields(v)})
}

// Represents a link to a photo.
type InlineQueryResultPhoto struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL of the photo.
	PhotoURL string `json:"photo_url"`
	// URL of the thumbnail for the photo
	ThumbnailURL string `json:"thumbnail_url"`
	// Width of the photo
	PhotoWidth *int `json:"photo_width,omitempty"`
	// Height of the photo
	PhotoHeight *int `json:"photo_height,omitempty"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Caption of the photo to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the photo caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the photo
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "photo".
func (v InlineQueryResultPhoto) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultPhoto
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"photo", fields(v)})
}

// Represents a link to an animated GIF file.
type InlineQueryResultGif struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL for the GIF file
	GifURL string `json:"gif_url"`
	// Width of the GIF
	GifWidth *int `json:"gif_width,omitempty"`
	// Height of the GIF
	GifHeight *int `json:"gif_height,omitempty"`
	// Duration of the GIF in seconds
	GifDuration *int `json:"gif_duration,omitempty"`
	// URL of the static (JPEG or GIF) or animated (MPEG4) thumbnail for the result
	ThumbnailURL string `json:"thumbnail_url"`
	// MIME type of the thumbnail, must be one of “image/jpeg”, “image/gif”, or
	// “video/mp4”.
	ThumbnailMimeType *string `json:"thumbnail_mime_type,omitempty"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Caption of the GIF file to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the GIF animation
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "gif".
func (v InlineQueryResultGif) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultGif
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"gif", fields(v)})
}

// Represents a link to a video animation (H.264/MPEG-4 AVC video without sound).
type InlineQueryResultMpeg4Gif struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL for the MPEG4 file
	Mpeg4URL string `json:"mpeg4_url"`
	// Video width
	Mpeg4Width *int `json:"mpeg4_width,omitempty"`
	// Video height
	Mpeg4Height *int `json:"mpeg4_height,omitempty"`
	// Video duration in seconds
	Mpeg4Duration *int `json:"mpeg4_duration,omitempty"`
	// URL of the static (JPEG or GIF) or animated (MPEG4) thumbnail for the result
	ThumbnailURL string `json:"thumbnail_url"`
	// MIME type of the thumbnail, must be one of “image/jpeg”, “image/gif”, or
	// “video/mp4”.
	ThumbnailMimeType *string `json:"thumbnail_mime_type,omitempty"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Caption of the MPEG-4 file to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the video animation
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "mpeg4_gif".
func (v InlineQueryResultMpeg4Gif) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultMpeg4Gif
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mpeg4_gif", fields(v)})
}

// Represents a link to a page containing an embedded video player or a video file.
type InlineQueryResultVideo struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL for the embedded video player or video file
	VideoURL string `json:"video_url"`
	// MIME type of the content of the video URL, “text/html” or “video/mp4”
	MimeType string `json:"mime_type"`
	// URL of the thumbnail (JPEG only) for the video
	ThumbnailURL string `json:"thumbnail_url"`
	// Title for the result
	Title string `json:"title"`
	// Caption of the video to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the video caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Video width
	VideoWidth *int `json:"video_width,omitempty"`
	// Video height
	VideoHeight *int `json:"video_height,omitempty"`
	// Video duration in seconds
	VideoDuration *int `json:"video_duration,omitempty"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the video.
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "video".
func (v InlineQueryResultVideo) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultVideo
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"video", fields(v)})
}

// Represents a link to an MP3 audio file.
type InlineQueryResultAudio struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL for the audio file
	AudioURL string `json:"audio_url"`
	// Title
	Title string `json:"title"`
	// Caption, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the audio caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Performer
	Performer *string `json:"performer,omitempty"`
	// Audio duration in seconds
	AudioDuration *int `json:"audio_duration,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the audio
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "audio".
func (v InlineQueryResultAudio) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultAudio
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"audio", fields(v)})
}

// Represents a link to a voice recording in an .OGG container encoded with OPUS.
type InlineQueryResultVoice struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid URL for the voice recording
	VoiceURL string `json:"voice_url"`
	// Recording title
	Title string `json:"title"`
	// Caption, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the voice message caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Recording duration in seconds
	VoiceDuration *int `json:"voice_duration,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the voice recording
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "voice".
func (v InlineQueryResultVoice) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultVoice
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"voice", fields(v)})
}

// Represents a link to a file.
type InlineQueryResultDocument struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// Title for the result
	Title string `json:"title"`
	// Caption of the document to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the document caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// A valid URL for the file
	DocumentURL string `json:"document_url"`
	// MIME type of the content of the file, either “application/pdf” or “application/zip”
	MimeType string `json:"mime_type"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the file
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
	// URL of the thumbnail (JPEG only) for the file
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Thumbnail width
	ThumbnailWidth *int `json:"thumbnail_width,omitempty"`
	// Thumbnail height
	ThumbnailHeight *int `json:"thumbnail_height,omitempty"`
}

// MarshalJSON encodes v with "type" set to "document".
func (v InlineQueryResultDocument) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultDocument
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"document", fields(v)})
}

// Represents a location on a map.
type InlineQueryResultLocation struct {
	// Unique identifier for this result, 1-64 Bytes
	ID string `json:"id"`
	// Location latitude in degrees
	Latitude float64 `json:"latitude"`
	// Location longitude in degrees
	Longitude float64 `json:"longitude"`
	// Location title
	Title string `json:"title"`
	// The radius of uncertainty for the location, measured in meters; 0-1500
	HorizontalAccuracy *float64 `json:"horizontal_accuracy,omitempty"`
	// Period in seconds during which the location can be updated, must be between 60 and 86400, or
	// 0x7FFFFFFF for live locations that can be edited indefinitely
	LivePeriod *int `json:"live_period,omitempty"`
	// For live locations, a direction in which the user is moving, in degrees.
	Heading *int `json:"heading,omitempty"`
	// For live locations, a maximum distance for proximity alerts about approaching another chat
	// member, in meters.
	ProximityAlertRadius *int `json:"proximity_alert_radius,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the location
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
	// Url of the thumbnail for the result
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Thumbnail width
	ThumbnailWidth *int `json:"thumbnail_width,omitempty"`
	// Thumbnail height
	ThumbnailHeight *int `json:"thumbnail_height,omitempty"`
}

// MarshalJSON encodes v with "type" set to "location".
func (v InlineQueryResultLocation) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultLocation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"location", fields(v)})
}

// Represents a venue.
type InlineQueryResultVenue struct {
	// Unique identifier for this result, 1-64 Bytes
	ID string `json:"id"`
	// Latitude of the venue location in degrees
	Latitude float64 `json:"latitude"`
	// Longitude of the venue location in degrees
	Longitude float64 `json:"longitude"`
	// Title of the venue
	Title string `json:"title"`
	// Address of the venue
	Address string `json:"address"`
	// Foursquare identifier of the venue if known
	FoursquareID *string `json:"foursquare_id,omitempty"`
	// Foursquare type of the venue, if known.
	FoursquareType *string `json:"foursquare_type,omitempty"`
	// Google Places identifier of the venue
	GooglePlaceID *string `json:"google_place_id,omitempty"`
	// Google Places type of the venue.
	GooglePlaceType *string `json:"google_place_type,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the venue
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
	// Url of the thumbnail for the result
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Thumbnail width
	ThumbnailWidth *int `json:"thumbnail_width,omitempty"`
	// Thumbnail height
	ThumbnailHeight *int `json:"thumbnail_height,omitempty"`
}

// MarshalJSON encodes v with "type" set to "venue".
func (v InlineQueryResultVenue) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultVenue
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"venue", fields(v)})
}

// Represents a contact with a phone number.
type InlineQueryResultContact struct {
	// Unique identifier for this result, 1-64 Bytes
	ID string `json:"id"`
	// Contact's phone number
	PhoneNumber string `json:"phone_number"`
	// Contact's first name
	FirstName string `json:"first_name"`
	// Contact's last name
	LastName *string `json:"last_name,omitempty"`
	// Additional data about the contact in the form of a vCard, 0-2048 bytes
	Vcard *string `json:"vcard,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the contact
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
	// Url of the thumbnail for the result
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Thumbnail width
	ThumbnailWidth *int `json:"thumbnail_width,omitempty"`
	// Thumbnail height
	ThumbnailHeight *int `json:"thumbnail_height,omitempty"`
}

// MarshalJSON encodes v with "type" set to "contact".
func (v InlineQueryResultContact) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultContact
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"contact", fields(v)})
}

// Represents a Game.
type InlineQueryResultGame struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// Short name of the game
	GameShortName string `json:"game_short_name"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
}

// MarshalJSON encodes v with "type" set to "game".
func (v InlineQueryResultGame) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultGame
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"game", fields(v)})
}

// Represents a link to a photo stored on the Telegram servers.
type InlineQueryResultCachedPhoto struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier of the photo
	PhotoFileID string `json:"photo_file_id"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Caption of the photo to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the photo caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the photo
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "photo".
func (v InlineQueryResultCachedPhoto) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedPhoto
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"photo", fields(v)})
}

// Represents a link to an animated GIF file stored on the Telegram servers.
type InlineQueryResultCachedGif struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier for the GIF file
	GifFileID string `json:"gif_file_id"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Caption of the GIF file to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the GIF animation
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "gif".
func (v InlineQueryResultCachedGif) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedGif
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"gif", fields(v)})
}

// Represents a link to a video animation (H.264/MPEG-4 AVC video without sound) stored on the
// Telegram servers.
type InlineQueryResultCachedMpeg4Gif struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier for the MPEG4 file
	Mpeg4FileID string `json:"mpeg4_file_id"`
	// Title for the result
	Title *string `json:"title,omitempty"`
	// Caption of the MPEG-4 file to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the video animation
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "mpeg4_gif".
func (v InlineQueryResultCachedMpeg4Gif) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedMpeg4Gif
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mpeg4_gif", fields(v)})
}

// Represents a link to a sticker stored on the Telegram servers.
type InlineQueryResultCachedSticker struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier of the sticker
	StickerFileID string `json:"sticker_file_id"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the sticker
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "sticker".
func (v InlineQueryResultCachedSticker) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedSticker
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"sticker", fields(v)})
}

// Represents a link to a file stored on the Telegram servers.
type InlineQueryResultCachedDocument struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// Title for the result
	Title string `json:"title"`
	// A valid file identifier for the file
	DocumentFileID string `json:"document_file_id"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Caption of the document to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the document caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the file
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "document".
func (v InlineQueryResultCachedDocument) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedDocument
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"document", fields(v)})
}

// Represents a link to a video file stored on the Telegram servers.
type InlineQueryResultCachedVideo struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier for the video file
	VideoFileID string `json:"video_file_id"`
	// Title for the result
	Title string `json:"title"`
	// Short description of the result
	Description *string `json:"description,omitempty"`
	// Caption of the video to be sent, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the video caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Pass True if the caption must be shown above the message media
	ShowCaptionAboveMedia *bool `json:"show_caption_above_media,omitempty"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the video
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "video".
func (v InlineQueryResultCachedVideo) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedVideo
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"video", fields(v)})
}

// Represents a link to a voice message stored on the Telegram servers.
type InlineQueryResultCachedVoice struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier for the voice message
	VoiceFileID string `json:"voice_file_id"`
	// Voice message title
	Title string `json:"title"`
	// Caption, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the voice message caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the voice message
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "voice".
func (v InlineQueryResultCachedVoice) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedVoice
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"voice", fields(v)})
}

// Represents a link to an MP3 audio file stored on the Telegram servers.
type InlineQueryResultCachedAudio struct {
	// Unique identifier for this result, 1-64 bytes
	ID string `json:"id"`
	// A valid file identifier for the audio file
	AudioFileID string `json:"audio_file_id"`
	// Caption, 0-1024 characters after entities parsing
	Caption *string `json:"caption,omitempty"`
	// Mode for parsing entities in the audio caption.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in the caption, which can be specified instead of
	// parse_mode
	CaptionEntities []MessageEntity `json:"caption_entities,omitzero"`
	// Inline keyboard attached to the message
	ReplyMarkup *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	// Content of the message to be sent instead of the audio
	InputMessageContent InputMessageContent `json:"input_message_content,omitempty"`
}

// MarshalJSON encodes v with "type" set to "audio".
func (v InlineQueryResultCachedAudio) MarshalJSON() ([]byte, error) {
	type fields InlineQueryResultCachedAudio
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"audio", fields(v)})
}

// InputMessageContent represents the content of a message to be sent as a result of an inline
// query.
//
// Implemented by *InputTextMessageContent, *InputRichMessageContent, *InputLocationMessageContent,
// *InputVenueMessageContent, *InputContactMessageContent and *InputInvoiceMessageContent.
type InputMessageContent interface{ inputMessageContent() }

func (*InputTextMessageContent) inputMessageContent()     {}
func (*InputRichMessageContent) inputMessageContent()     {}
func (*InputLocationMessageContent) inputMessageContent() {}
func (*InputVenueMessageContent) inputMessageContent()    {}
func (*InputContactMessageContent) inputMessageContent()  {}
func (*InputInvoiceMessageContent) inputMessageContent()  {}

// Represents the content of a text message to be sent as the result of an inline query.
type InputTextMessageContent struct {
	// Text of the message to be sent, 1-4096 characters
	MessageText string `json:"message_text"`
	// Mode for parsing entities in the message text.
	ParseMode *string `json:"parse_mode,omitempty"`
	// List of special entities that appear in message text, which can be specified instead of
	// parse_mode
	Entities []MessageEntity `json:"entities,omitzero"`
	// Link preview generation options for the message
	LinkPreviewOptions *LinkPreviewOptions `json:"link_preview_options,omitempty"`
}

// Represents the content of a rich message to be sent as the result of an inline query.
type InputRichMessageContent struct {
	// The message to be sent.
	RichMessage InputRichMessage `json:"rich_message"`
}

// Represents the content of a location message to be sent as the result of an inline query.
type InputLocationMessageContent struct {
	// Latitude of the location in degrees
	Latitude float64 `json:"latitude"`
	// Longitude of the location in degrees
	Longitude float64 `json:"longitude"`
	// The radius of uncertainty for the location, measured in meters; 0-1500
	HorizontalAccuracy *float64 `json:"horizontal_accuracy,omitempty"`
	// Period in seconds during which the location can be updated, must be between 60 and 86400, or
	// 0x7FFFFFFF for live locations that can be edited indefinitely
	LivePeriod *int `json:"live_period,omitempty"`
	// For live locations, a direction in which the user is moving, in degrees.
	Heading *int `json:"heading,omitempty"`
	// For live locations, a maximum distance for proximity alerts about approaching another chat
	// member, in meters.
	ProximityAlertRadius *int `json:"proximity_alert_radius,omitempty"`
}

// Represents the content of a venue message to be sent as the result of an inline query.
type InputVenueMessageContent struct {
	// Latitude of the venue in degrees
	Latitude float64 `json:"latitude"`
	// Longitude of the venue in degrees
	Longitude float64 `json:"longitude"`
	// Name of the venue
	Title string `json:"title"`
	// Address of the venue
	Address string `json:"address"`
	// Foursquare identifier of the venue, if known
	FoursquareID *string `json:"foursquare_id,omitempty"`
	// Foursquare type of the venue, if known.
	FoursquareType *string `json:"foursquare_type,omitempty"`
	// Google Places identifier of the venue
	GooglePlaceID *string `json:"google_place_id,omitempty"`
	// Google Places type of the venue.
	GooglePlaceType *string `json:"google_place_type,omitempty"`
}

// Represents the content of a contact message to be sent as the result of an inline query.
type InputContactMessageContent struct {
	// Contact's phone number
	PhoneNumber string `json:"phone_number"`
	// Contact's first name
	FirstName string `json:"first_name"`
	// Contact's last name
	LastName *string `json:"last_name,omitempty"`
	// Additional data about the contact in the form of a vCard, 0-2048 bytes
	Vcard *string `json:"vcard,omitempty"`
}

// Represents the content of an invoice message to be sent as the result of an inline query.
type InputInvoiceMessageContent struct {
	// Product name, 1-32 characters
	Title string `json:"title"`
	// Product description, 1-255 characters
	Description string `json:"description"`
	// Bot-defined invoice payload, 1-128 bytes.
	Payload string `json:"payload"`
	// Payment provider token, obtained via @BotFather.
	ProviderToken *string `json:"provider_token,omitempty"`
	// Three-letter ISO 4217 currency code, see more on currencies.
	Currency string `json:"currency"`
	// Price breakdown, a JSON-serialized list of components (e.g. product price, tax, discount,
	// delivery cost, delivery tax, bonus, etc.).
	Prices []LabeledPrice `json:"prices"`
	// The maximum accepted amount for tips in the smallest units of the currency (integer, not
	// float/double).
	MaxTipAmount *int `json:"max_tip_amount,omitempty"`
	// A JSON-serialized Array of suggested amounts of tip in the smallest units of the currency
	// (integer, not float/double).
	SuggestedTipAmounts []int `json:"suggested_tip_amounts,omitzero"`
	// A JSON-serialized object for data about the invoice, which will be shared with the payment
	// provider.
	ProviderData *string `json:"provider_data,omitempty"`
	// URL of the product photo for the invoice.
	PhotoURL *string `json:"photo_url,omitempty"`
	// Photo size in bytes
	PhotoSize *int `json:"photo_size,omitempty"`
	// Photo width
	PhotoWidth *int `json:"photo_width,omitempty"`
	// Photo height
	PhotoHeight *int `json:"photo_height,omitempty"`
	// Pass True if you require the user's full name to complete the order.
	NeedName *bool `json:"need_name,omitempty"`
	// Pass True if you require the user's phone number to complete the order.
	NeedPhoneNumber *bool `json:"need_phone_number,omitempty"`
	// Pass True if you require the user's email address to complete the order.
	NeedEmail *bool `json:"need_email,omitempty"`
	// Pass True if you require the user's shipping address to complete the order.
	NeedShippingAddress *bool `json:"need_shipping_address,omitempty"`
	// Pass True if the user's phone number should be sent to the provider.
	SendPhoneNumberToProvider *bool `json:"send_phone_number_to_provider,omitempty"`
	// Pass True if the user's email address should be sent to the provider.
	SendEmailToProvider *bool `json:"send_email_to_provider,omitempty"`
	// Pass True if the final price depends on the shipping method.
	IsFlexible *bool `json:"is_flexible,omitempty"`
}

// Represents a result of an inline query that was chosen by the user and sent to their chat
// partner.
type ChosenInlineResult struct {
	// The unique identifier for the result that was chosen
	ResultID string `json:"result_id"`
	// The user that chose the result
	From User `json:"from"`
	// Sender location, only for bots that require user location
	Location *Location `json:"location,omitempty"`
	// Identifier of the sent inline message.
	InlineMessageID *string `json:"inline_message_id,omitempty"`
	// The query that was used to obtain the result
	Query string `json:"query"`
}
