// Code generated by teleiq-gen. DO NOT EDIT.

package models

import "encoding/json"

// Describes Telegram Passport data shared with the bot by the user.
type PassportData struct {
	// Array with information about documents and other Telegram Passport elements that was shared with
	// the bot
	Data []EncryptedPassportElement `json:"data"`
	// Encrypted credentials required to decrypt the data
	Credentials EncryptedCredentials `json:"credentials"`
}

// PassportFile represents a file uploaded to Telegram Passport.
type PassportFile struct {
	// Identifier for this file, which can be used to download or reuse the file
	FileID string `json:"file_id"`
	// Unique identifier for this file, which is supposed to be the same over time and for different
	// bots.
	FileUniqueID string `json:"file_unique_id"`
	// File size in bytes
	FileSize int64 `json:"file_size"`
	// Unix time when the file was uploaded
	FileDate int64 `json:"file_date"`
}

// Describes documents or other Telegram Passport elements shared with the bot by the user.
type EncryptedPassportElement struct {
	// Element type.
	Type string `json:"type"`
	// Base64-encoded encrypted Telegram Passport element data provided by the user; available only for
	// “personal_details”, “passport”, “driver_license”, “identity_card”,
	// “internal_passport” and “address” types.
	Data *string `json:"data,omitempty"`
	// User's verified phone number; available only for “phone_number” type
	PhoneNumber *string `json:"phone_number,omitempty"`
	// User's verified email address; available only for “email” type
	Email *string `json:"email,omitempty"`
	// Array of encrypted files with documents provided by the user; available only for
	// “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”
	// and “temporary_registration” types.
	Files []PassportFile `json:"files,omitzero"`
	// Encrypted file with the front side of the document, provided by the user; available only for
	// “passport”, “driver_license”, “identity_card” and “internal_passport”.
	FrontSide *PassportFile `json:"front_side,omitempty"`
	// Encrypted file with the reverse side of the document, provided by the user; available only for
	// “driver_license” and “identity_card”.
	ReverseSide *PassportFile `json:"reverse_side,omitempty"`
	// Encrypted file with the selfie of the user holding a document, provided by the user; available
	// if requested for “passport”, “driver_license”, “identity_card” and
	// “internal_passport”.
	Selfie *PassportFile `json:"selfie,omitempty"`
	// Array of encrypted files with translated versions of documents provided by the user; available
	// if requested for “passport”, “driver_license”, “identity_card”,
	// “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”,
	// “passport_registration” and “temporary_registration” types.
	Translation []PassportFile `json:"translation,omitzero"`
	// Base64-encoded element hash for using in PassportElementErrorUnspecified
	Hash string `json:"hash"`
}

// Describes data required for decrypting and authenticating EncryptedPassportElement.
type EncryptedCredentials struct {
	// Base64-encoded encrypted JSON-serialized data with unique user's payload, data hashes and
	// secrets required for EncryptedPassportElement decryption and authentication
	Data string `json:"data"`
	// Base64-encoded data hash for data authentication
	Hash string `json:"hash"`
	// Base64-encoded secret, encrypted with the bot's public RSA key, required for data decryption
	Secret string `json:"secret"`
}

// PassportElementError represents an error in the Telegram Passport element which was submitted
// that should be resolved by the user.
//
// Implemented by *PassportElementErrorDataField, *PassportElementErrorFrontSide,
// *PassportElementErrorReverseSide, *PassportElementErrorSelfie, *PassportElementErrorFile,
// *PassportElementErrorFiles, *PassportElementErrorTranslationFile,
// *PassportElementErrorTranslationFiles and *PassportElementErrorUnspecified.
type PassportElementError interface{ passportElementError() }

func (*PassportElementErrorDataField) passportElementError()        {}
func (*PassportElementErrorFrontSide) passportElementError()        {}
func (*PassportElementErrorReverseSide) passportElementError()      {}
func (*PassportElementErrorSelfie) passportElementError()           {}
func (*PassportElementErrorFile) passportElementError()             {}
func (*PassportElementErrorFiles) passportElementError()            {}
func (*PassportElementErrorTranslationFile) passportElementError()  {}
func (*PassportElementErrorTranslationFiles) passportElementError() {}
func (*PassportElementErrorUnspecified) passportElementError()      {}

// Represents an issue in one of the data fields that was provided by the user.
type PassportElementErrorDataField struct {
	// The section of the user's Telegram Passport which has the error, one of “personal_details”,
	// “passport”, “driver_license”, “identity_card”, “internal_passport”,
	// “address”
	Type string `json:"type"`
	// Name of the data field which has the error
	FieldName string `json:"field_name"`
	// Base64-encoded data hash
	DataHash string `json:"data_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "data".
func (v PassportElementErrorDataField) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorDataField
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"data", fields(v)})
}

// Represents an issue with the front side of a document.
type PassportElementErrorFrontSide struct {
	// The section of the user's Telegram Passport which has the issue, one of “passport”,
	// “driver_license”, “identity_card”, “internal_passport”
	Type string `json:"type"`
	// Base64-encoded hash of the file with the front side of the document
	FileHash string `json:"file_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "front_side".
func (v PassportElementErrorFrontSide) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorFrontSide
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"front_side", fields(v)})
}

// Represents an issue with the reverse side of a document.
type PassportElementErrorReverseSide struct {
	// The section of the user's Telegram Passport which has the issue, one of “driver_license”,
	// “identity_card”
	Type string `json:"type"`
	// Base64-encoded hash of the file with the reverse side of the document
	FileHash string `json:"file_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "reverse_side".
func (v PassportElementErrorReverseSide) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorReverseSide
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"reverse_side", fields(v)})
}

// Represents an issue with the selfie with a document.
type PassportElementErrorSelfie struct {
	// The section of the user's Telegram Passport which has the issue, one of “passport”,
	// “driver_license”, “identity_card”, “internal_passport”
	Type string `json:"type"`
	// Base64-encoded hash of the file with the selfie
	FileHash string `json:"file_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "selfie".
func (v PassportElementErrorSelfie) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorSelfie
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"selfie", fields(v)})
}

// Represents an issue with a document scan.
type PassportElementErrorFile struct {
	// The section of the user's Telegram Passport which has the issue, one of “utility_bill”,
	// “bank_statement”, “rental_agreement”, “passport_registration”,
	// “temporary_registration”
	Type string `json:"type"`
	// Base64-encoded file hash
	FileHash string `json:"file_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "file".
func (v PassportElementErrorFile) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorFile
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"file", fields(v)})
}

// Represents an issue with a list of scans.
type PassportElementErrorFiles struct {
	// The section of the user's Telegram Passport which has the issue, one of “utility_bill”,
	// “bank_statement”, “rental_agreement”, “passport_registration”,
	// “temporary_registration”
	Type string `json:"type"`
	// List of base64-encoded file hashes
	FileHashes []string `json:"file_hashes"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "files".
func (v PassportElementErrorFiles) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorFiles
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"files", fields(v)})
}

// Represents an issue with one of the files that constitute the translation of a document.
type PassportElementErrorTranslationFile struct {
	// Type of element of the user's Telegram Passport which has the issue, one of “passport”,
	// “driver_license”, “identity_card”, “internal_passport”, “utility_bill”,
	// “bank_statement”, “rental_agreement”, “passport_registration”,
	// “temporary_registration”
	Type string `json:"type"`
	// Base64-encoded file hash
	FileHash string `json:"file_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "translation_file".
func (v PassportElementErrorTranslationFile) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorTranslationFile
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"translation_file", fields(v)})
}

// Represents an issue with the translated version of a document.
type PassportElementErrorTranslationFiles struct {
	// Type of element of the user's Telegram Passport which has the issue, one of “passport”,
	// “driver_license”, “identity_card”, “internal_passport”, “utility_bill”,
	// “bank_statement”, “rental_agreement”, “passport_registration”,
	// “temporary_registration”
	Type string `json:"type"`
	// List of base64-encoded file hashes
	FileHashes []string `json:"file_hashes"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "translation_files".
func (v PassportElementErrorTranslationFiles) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorTranslationFiles
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"translation_files", fields(v)})
}

// Represents an issue in an unspecified place.
type PassportElementErrorUnspecified struct {
	// Type of element of the user's Telegram Passport which has the issue
	Type string `json:"type"`
	// Base64-encoded element hash
	ElementHash string `json:"element_hash"`
	// Error message
	Message string `json:"message"`
}

// MarshalJSON encodes v with "source" set to "unspecified".
func (v PassportElementErrorUnspecified) MarshalJSON() ([]byte, error) {
	type fields PassportElementErrorUnspecified
	return json.Marshal(struct {
		Source string `json:"source"`
		fields
	}{"unspecified", fields(v)})
}
