// Code generated by teleiq-gen. DO NOT EDIT.

package models

import "encoding/json"

// LabeledPrice represents a portion of the price for goods or services.
type LabeledPrice struct {
	// Portion label
	Label string `json:"label"`
	// Price of the product in the smallest units of the currency (integer, not float/double).
	Amount int `json:"amount"`
}

// Invoice contains basic information about an invoice.
type Invoice struct {
	// Product name
	Title string `json:"title"`
	// Product description
	Description string `json:"description"`
	// Unique bot deep-linking parameter that can be used to generate this invoice
	StartParameter string `json:"start_parameter"`
	// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
	Currency string `json:"currency"`
	// Total price in the smallest units of the currency (integer, not float/double).
	TotalAmount int `json:"total_amount"`
}

// ShippingAddress represents a shipping address.
type ShippingAddress struct {
	// Two-letter ISO 3166-1 alpha-2 country code
	CountryCode string `json:"country_code"`
	// State, if applicable
	State string `json:"state"`
	// City
	City string `json:"city"`
	// First line for the address
	StreetLine1 string `json:"street_line1"`
	// Second line for the address
	StreetLine2 string `json:"street_line2"`
	// Address post code
	PostCode string `json:"post_code"`
}

// OrderInfo represents information about an order.
type OrderInfo struct {
	// User name
	Name *string `json:"name,omitempty"`
	// User's phone number
	PhoneNumber *string `json:"phone_number,omitempty"`
	// User email
	Email *string `json:"email,omitempty"`
	// User shipping address
	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`
}

// ShippingOption represents one shipping option.
type ShippingOption struct {
	// Shipping option identifier
	ID string `json:"id"`
	// Option title
	Title string `json:"title"`
	// List of price portions
	Prices []LabeledPrice `json:"prices"`
}

// SuccessfulPayment contains basic information about a successful payment.
type SuccessfulPayment struct {
	// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
	Currency string `json:"currency"`
	// Total price in the smallest units of the currency (integer, not float/double).
	TotalAmount int `json:"total_amount"`
	// Bot-specified invoice payload
	InvoicePayload string `json:"invoice_payload"`
	// Expiration date of the subscription, in Unix time; for recurring payments only
	SubscriptionExpirationDate *int64 `json:"subscription_expiration_date,omitempty"`
	// True, if the payment is a recurring payment for a subscription
	IsRecurring bool `json:"is_recurring,omitempty"`
	// True, if the payment is the first payment for a subscription
	IsFirstRecurring bool `json:"is_first_recurring,omitempty"`
	// Identifier of the shipping option chosen by the user
	ShippingOptionID *string `json:"shipping_option_id,omitempty"`
	// Order information provided by the user
	OrderInfo *OrderInfo `json:"order_info,omitempty"`
	// Telegram payment identifier
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"`
	// Provider payment identifier
	ProviderPaymentChargeID string `json:"provider_payment_charge_id"`
}

// RefundedPayment contains basic information about a refunded payment.
type RefundedPayment struct {
	// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars.
	Currency string `json:"currency"`
	// Total refunded price in the smallest units of the currency (integer, not float/double).
	TotalAmount int `json:"total_amount"`
	// Bot-specified invoice payload
	InvoicePayload string `json:"invoice_payload"`
	// Telegram payment identifier
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"`
	// Provider payment identifier
	ProviderPaymentChargeID *string `json:"provider_payment_charge_id,omitempty"`
}

// ShippingQuery contains information about an incoming shipping query.
type ShippingQuery struct {
	// Unique query identifier
	ID string `json:"id"`
	// User who sent the query
	From User `json:"from"`
	// Bot-specified invoice payload
	InvoicePayload string `json:"invoice_payload"`
	// User specified shipping address
	ShippingAddress ShippingAddress `json:"shipping_address"`
}

// PreCheckoutQuery contains information about an incoming pre-checkout query.
type PreCheckoutQuery struct {
	// Unique query identifier
	ID string `json:"id"`
	// User who sent the query
	From User `json:"from"`
	// Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
	Currency string `json:"currency"`
	// Total price in the smallest units of the currency (integer, not float/double).
	TotalAmount int `json:"total_amount"`
	// Bot-specified invoice payload
	InvoicePayload string `json:"invoice_payload"`
	// Identifier of the shipping option chosen by the user
	ShippingOptionID *string `json:"shipping_option_id,omitempty"`
	// Order information provided by the user
	OrderInfo *OrderInfo `json:"order_info,omitempty"`
}

// PaidMediaPurchased contains information about a paid media purchase.
type PaidMediaPurchased struct {
	// User who purchased the media
	From User `json:"from"`
	// Bot-specified paid media payload
	PaidMediaPayload string `json:"paid_media_payload"`
}

// RevenueWithdrawalState describes the state of a revenue withdrawal operation.
//
// Implemented by *RevenueWithdrawalStatePending, *RevenueWithdrawalStateSucceeded,
// *RevenueWithdrawalStateFailed and *Unknown.
type RevenueWithdrawalState interface{ revenueWithdrawalState() }

func (*RevenueWithdrawalStatePending) revenueWithdrawalState()   {}
func (*RevenueWithdrawalStateSucceeded) revenueWithdrawalState() {}
func (*RevenueWithdrawalStateFailed) revenueWithdrawalState()    {}
func (*Unknown) revenueWithdrawalState()                         {}

func decodeRevenueWithdrawalState(data []byte) (RevenueWithdrawalState, error) {
	if isNull(data) {
		return nil, nil
	}
	var head struct {
		Kind string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	var v RevenueWithdrawalState
	switch head.Kind {
	case "pending":
		v = new(RevenueWithdrawalStatePending)
	case "succeeded":
		v = new(RevenueWithdrawalStateSucceeded)
	case "failed":
		v = new(RevenueWithdrawalStateFailed)
	default:
		return newUnknown(head.Kind, data), nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return nil, err
	}
	return v, nil
}

// The withdrawal is in progress.
type RevenueWithdrawalStatePending struct{}

// MarshalJSON encodes v with "type" set to "pending".
func (v RevenueWithdrawalStatePending) MarshalJSON() ([]byte, error) {
	type fields RevenueWithdrawalStatePending
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"pending", fields(v)})
}

// The withdrawal succeeded.
type RevenueWithdrawalStateSucceeded struct {
	// Date the withdrawal was completed in Unix time
	Date int64 `json:"date"`
	// An HTTPS URL that can be used to see transaction details
	URL string `json:"url"`
}

// MarshalJSON encodes v with "type" set to "succeeded".
func (v RevenueWithdrawalStateSucceeded) MarshalJSON() ([]byte, error) {
	type fields RevenueWithdrawalStateSucceeded
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"succeeded", fields(v)})
}

// The withdrawal failed and the transaction was refunded.
type RevenueWithdrawalStateFailed struct{}

// MarshalJSON encodes v with "type" set to "failed".
func (v RevenueWithdrawalStateFailed) MarshalJSON() ([]byte, error) {
	type fields RevenueWithdrawalStateFailed
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"failed", fields(v)})
}

// Contains information about the affiliate that received a commission via this transaction.
type AffiliateInfo struct {
	// The bot or the user that received an affiliate commission if it was received by a bot or a user
	AffiliateUser *User `json:"affiliate_user,omitempty"`
	// The chat that received an affiliate commission if it was received by a chat
	AffiliateChat *Chat `json:"affiliate_chat,omitempty"`
	// The number of Telegram Stars received by the affiliate for each 1000 Telegram Stars received by
	// the bot from referred users
	CommissionPerMille int `json:"commission_per_mille"`
	// Integer amount of Telegram Stars received by the affiliate from the transaction, rounded to 0;
	// can be negative for refunds
	Amount int `json:"amount"`
	// The number of 1/1000000000 shares of Telegram Stars received by the affiliate; from -999999999
	// to 999999999; can be negative for refunds
	NanostarAmount *int `json:"nanostar_amount,omitempty"`
}

// TransactionPartner describes the source of a transaction, or its recipient for outgoing
// transactions.
//
// Implemented by *TransactionPartnerUser, *TransactionPartnerChat,
// *TransactionPartnerAffiliateProgram, *TransactionPartnerFragment, *TransactionPartnerTelegramAds,
// *TransactionPartnerTelegramApi, *TransactionPartnerOther and *Unknown.
type TransactionPartner interface{ transactionPartner() }

func (*TransactionPartnerUser) transactionPartner()             {}
func (*TransactionPartnerChat) transactionPartner()             {}
func (*TransactionPartnerAffiliateProgram) transactionPartner() {}
func (*TransactionPartnerFragment) transactionPartner()         {}
func (*TransactionPartnerTelegramAds) transactionPartner()      {}
func (*TransactionPartnerTelegramApi) transactionPartner()      {}
func (*TransactionPartnerOther) transactionPartner()            {}
func (*Unknown) transactionPartner()                            {}

func decodeTransactionPartner(data []byte) (TransactionPartner, error) {
	if isNull(data) {
		return nil, nil
	}
	var head struct {
		Kind string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	var v TransactionPartner
	switch head.Kind {
	case "user":
		v = new(TransactionPartnerUser)
	case "chat":
		v = new(TransactionPartnerChat)
	case "affiliate_program":
		v = new(TransactionPartnerAffiliateProgram)
	case "fragment":
		v = new(TransactionPartnerFragment)
	case "telegram_ads":
		v = new(TransactionPartnerTelegramAds)
	case "telegram_api":
		v = new(TransactionPartnerTelegramApi)
	case "other":
		v = new(TransactionPartnerOther)
	default:
		return newUnknown(head.Kind, data), nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return nil, err
	}
	return v, nil
}

// Describes a transaction with a user.
type TransactionPartnerUser struct {
	// Type of the transaction, currently one of “invoice_payment” for payments via invoices,
	// “paid_media_payment” for payments for paid media, “gift_purchase” for gifts sent by the
	// bot, “premium_purchase” for Telegram Premium subscriptions gifted by the bot,
	// “business_account_transfer” for direct transfers from managed business accounts
	TransactionType string `json:"transaction_type"`
	// Information about the user
	User User `json:"user"`
	// Information about the affiliate that received a commission via this transaction.
	Affiliate *AffiliateInfo `json:"affiliate,omitempty"`
	// Bot-specified invoice payload.
	InvoicePayload *string `json:"invoice_payload,omitempty"`
	// The duration of the paid subscription.
	SubscriptionPeriod *int `json:"subscription_period,omitempty"`
	// Information about the paid media bought by the user; for “paid_media_payment” transactions
	// only
	PaidMedia []PaidMedia `json:"paid_media,omitzero"`
	// Bot-specified paid media payload.
	PaidMediaPayload *string `json:"paid_media_payload,omitempty"`
	// The gift sent to the user by the bot; for “gift_purchase” transactions only
	Gift *Gift `json:"gift,omitempty"`
	// Number of months the gifted Telegram Premium subscription will be active for; for
	// “premium_purchase” transactions only
	PremiumSubscriptionDuration *int `json:"premium_subscription_duration,omitempty"`
}

// MarshalJSON encodes v with "type" set to "user".
func (v TransactionPartnerUser) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerUser
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"user", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *TransactionPartnerUser) UnmarshalJSON(data []byte) error {
	type fields TransactionPartnerUser
	var raw struct {
		*fields
		PaidMedia []json.RawMessage `json:"paid_media"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.PaidMedia, err = decodeEach(raw.PaidMedia, decodePaidMedia); err != nil {
		return err
	}
	return nil
}

// Describes a transaction with a chat.
type TransactionPartnerChat struct {
	// Information about the chat
	Chat Chat `json:"chat"`
	// The gift sent to the chat by the bot
	Gift *Gift `json:"gift,omitempty"`
}

// MarshalJSON encodes v with "type" set to "chat".
func (v TransactionPartnerChat) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerChat
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"chat", fields(v)})
}

// Describes the affiliate program that issued the affiliate commission received via this
// transaction.
type TransactionPartnerAffiliateProgram struct {
	// Information about the bot that sponsored the affiliate program
	SponsorUser *User `json:"sponsor_user,omitempty"`
	// The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the
	// affiliate program sponsor from referred users
	CommissionPerMille int `json:"commission_per_mille"`
}

// MarshalJSON encodes v with "type" set to "affiliate_program".
func (v TransactionPartnerAffiliateProgram) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerAffiliateProgram
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"affiliate_program", fields(v)})
}

// Describes a withdrawal transaction with Fragment.
type TransactionPartnerFragment struct {
	// State of the transaction if the transaction is outgoing
	WithdrawalState RevenueWithdrawalState `json:"withdrawal_state,omitempty"`
}

// MarshalJSON encodes v with "type" set to "fragment".
func (v TransactionPartnerFragment) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerFragment
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"fragment", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *TransactionPartnerFragment) UnmarshalJSON(data []byte) error {
	type fields TransactionPartnerFragment
	var raw struct {
		*fields
		WithdrawalState json.RawMessage `json:"withdrawal_state"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.WithdrawalState, err = decodeRevenueWithdrawalState(raw.WithdrawalState); err != nil {
		return err
	}
	return nil
}

// Describes a withdrawal transaction to the Telegram Ads platform.
type TransactionPartnerTelegramAds struct{}

// MarshalJSON encodes v with "type" set to "telegram_ads".
func (v TransactionPartnerTelegramAds) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerTelegramAds
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"telegram_ads", fields(v)})
}

// Describes a transaction with payment for paid broadcasting.
type TransactionPartnerTelegramApi struct {
	// The number of successful requests that exceeded regular limits and were therefore billed
	RequestCount int `json:"request_count"`
}

// MarshalJSON encodes v with "type" set to "telegram_api".
func (v TransactionPartnerTelegramApi) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerTelegramApi
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"telegram_api", fields(v)})
}

// Describes a transaction with an unknown source or recipient.
type TransactionPartnerOther struct{}

// MarshalJSON encodes v with "type" set to "other".
func (v TransactionPartnerOther) MarshalJSON() ([]byte, error) {
	type fields TransactionPartnerOther
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"other", fields(v)})
}

// Describes a Telegram Star transaction.
type StarTransaction struct {
	// Unique identifier of the transaction.
	ID string `json:"id"`
	// Integer amount of Telegram Stars transferred by the transaction
	Amount int `json:"amount"`
	// The number of 1/1000000000 shares of Telegram Stars transferred by the transaction; from 0 to
	// 999999999
	NanostarAmount *int `json:"nanostar_amount,omitempty"`
	// Date the transaction was created in Unix time
	Date int64 `json:"date"`
	// Source of an incoming transaction (e.g., a user purchasing goods or services, Fragment refunding
	// a failed withdrawal).
	Source TransactionPartner `json:"source,omitempty"`
	// Receiver of an outgoing transaction (e.g., a user for a purchase refund, Fragment for a
	// withdrawal).
	Receiver TransactionPartner `json:"receiver,omitempty"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *StarTransaction) UnmarshalJSON(data []byte) error {
	type fields StarTransaction
	var raw struct {
		*fields
		Source   json.RawMessage `json:"source"`
		Receiver json.RawMessage `json:"receiver"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Source, err = decodeTransactionPartner(raw.Source); err != nil {
		return err
	}
	if v.Receiver, err = decodeTransactionPartner(raw.Receiver); err != nil {
		return err
	}
	return nil
}

// Contains a list of Telegram Star transactions.
type StarTransactions struct {
	// The list of transactions
	Transactions []StarTransaction `json:"transactions"`
}
