// Code generated by teleiq-gen. DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
)

// Rich formatted message.
type RichMessage struct {
	// Content of the message
	Blocks []RichBlock `json:"blocks"`
	// True, if the rich message must be shown right-to-left
	IsRTL *bool `json:"is_rtl,omitempty"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichMessage) UnmarshalJSON(data []byte) error {
	type fields RichMessage
	var raw struct {
		*fields
		Blocks []json.RawMessage `json:"blocks"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	return nil
}

// Describes a rich message to be sent.
type InputRichMessage struct {
	// Content of the rich message to send described as a list of blocks
	Blocks []InputRichBlock `json:"blocks,omitzero"`
	// Content of the rich message to send described using HTML formatting.
	HTML *string `json:"html,omitempty"`
	// Content of the rich message to send described using Markdown formatting.
	Markdown *string `json:"markdown,omitempty"`
	// List of media that are specified in the markdown or html fields using tg://photo?id=,
	// tg://video?id=, tg://document?id=, and tg://audio?id= links
	Media []InputRichMessageMedia `json:"media,omitzero"`
	// Pass True if the rich message must be shown right-to-left
	IsRTL *bool `json:"is_rtl,omitempty"`
	// Pass True to skip automatic detection of entities (e.g., URLs, email addresses, username
	// mentions, hashtags, cashtags, bot commands, or phone numbers) in the text
	SkipEntityDetection *bool `json:"skip_entity_detection,omitempty"`
}

// Describes a media element embedded in an outgoing rich message.
type InputRichMessageMedia struct {
	// Unique identifier of the media used in a tg://photo?id=, tg://video?id=, tg://document?id=, or
	// tg://audio?id= link.
	ID string `json:"id"`
	// The media to be sent.
	Media InputRichMedia `json:"media"`
}

// RichMessageButton represents a button in a RichMessage.
type RichMessageButton struct {
	// Text of the button.
	Text RichText `json:"text"`
	// Style of the button.
	Style *string `json:"style,omitempty"`
	// HTTP or tg:// URL to be opened when the button is pressed.
	URL *string `json:"url,omitempty"`
	// Data to be sent in a callback query to the bot when the button is pressed, 1-64 bytes
	CallbackData *string `json:"callback_data,omitempty"`
	// Description of the Web App that will be launched when the user presses the button.
	WebApp *WebAppInfo `json:"web_app,omitempty"`
	// An HTTPS URL used to automatically authorize the user.
	LoginURL *LoginUrl `json:"login_url,omitempty"`
	// If set, pressing the button will prompt the user to select one of their chats, open that chat
	// and insert the bot's username and the specified inline query in the input field.
	SwitchInlineQuery *string `json:"switch_inline_query,omitempty"`
	// If set, pressing the button will insert the bot's username and the specified inline query in the
	// current chat's input field.
	SwitchInlineQueryCurrentChat *string `json:"switch_inline_query_current_chat,omitempty"`
	// If set, pressing the button will prompt the user to select one of their chats of the specified
	// type, open that chat and insert the bot's username and the specified inline query in the input
	// field.
	SwitchInlineQueryChosenChat *SwitchInlineQueryChosenChat `json:"switch_inline_query_chosen_chat,omitempty"`
	// A button that copies the specified text to the clipboard
	CopyText *CopyTextButton `json:"copy_text,omitempty"`
	// If set, then the button is disabled and does nothing
	Disabled *DisabledButton `json:"disabled,omitempty"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichMessageButton) UnmarshalJSON(data []byte) error {
	type fields RichMessageButton
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// RichText represents a rich formatted text.
//
// Implemented by RichTextString, RichTextArray, *RichTextBold, *RichTextItalic, *RichTextUnderline,
// *RichTextStrikethrough, *RichTextSpoiler, *RichTextDateTime, *RichTextTextMention,
// *RichTextSubscript, *RichTextSuperscript, *RichTextMarked, *RichTextCode, *RichTextCustomEmoji,
// *RichTextMathematicalExpression, *RichTextUrl, *RichTextEmailAddress, *RichTextPhoneNumber,
// *RichTextBankCardNumber, *RichTextMention, *RichTextHashtag, *RichTextCashtag,
// *RichTextBotCommand, *RichTextButton, *RichTextAnchor, *RichTextAnchorLink, *RichTextReference,
// *RichTextReferenceLink and *Unknown.
type RichText interface{ richText() }

// RichTextString is plain text in a RichText.
type RichTextString string

// RichTextArray is a sequence of RichText parts.
type RichTextArray []RichText

func (RichTextString) richText()                  {}
func (RichTextArray) richText()                   {}
func (*RichTextBold) richText()                   {}
func (*RichTextItalic) richText()                 {}
func (*RichTextUnderline) richText()              {}
func (*RichTextStrikethrough) richText()          {}
func (*RichTextSpoiler) richText()                {}
func (*RichTextDateTime) richText()               {}
func (*RichTextTextMention) richText()            {}
func (*RichTextSubscript) richText()              {}
func (*RichTextSuperscript) richText()            {}
func (*RichTextMarked) richText()                 {}
func (*RichTextCode) richText()                   {}
func (*RichTextCustomEmoji) richText()            {}
func (*RichTextMathematicalExpression) richText() {}
func (*RichTextUrl) richText()                    {}
func (*RichTextEmailAddress) richText()           {}
func (*RichTextPhoneNumber) richText()            {}
func (*RichTextBankCardNumber) richText()         {}
func (*RichTextMention) richText()                {}
func (*RichTextHashtag) richText()                {}
func (*RichTextCashtag) richText()                {}
func (*RichTextBotCommand) richText()             {}
func (*RichTextButton) richText()                 {}
func (*RichTextAnchor) richText()                 {}
func (*RichTextAnchorLink) richText()             {}
func (*RichTextReference) richText()              {}
func (*RichTextReferenceLink) richText()          {}
func (*Unknown) richText()                        {}

func decodeRichText(data []byte) (RichText, error) {
	switch data = bytes.TrimSpace(data); {
	case isNull(data):
		return nil, nil
	case data[0] == '"':
		var text RichTextString
		if err := json.Unmarshal(data, &text); err != nil {
			return nil, err
		}
		return text, nil
	case data[0] == '[':
		var raws []json.RawMessage
		if err := json.Unmarshal(data, &raws); err != nil {
			return nil, err
		}
		parts, err := decodeEach(raws, decodeRichText)
		if err != nil {
			return nil, err
		}
		return RichTextArray(parts), nil
	}
	return decodeRichTextObject(data)
}

func decodeRichTextObject(data []byte) (RichText, error) {
	if isNull(data) {
		return nil, nil
	}
	var head struct {
		Kind string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	var v RichText
	switch head.Kind {
	case "bold":
		v = new(RichTextBold)
	case "italic":
		v = new(RichTextItalic)
	case "underline":
		v = new(RichTextUnderline)
	case "strikethrough":
		v = new(RichTextStrikethrough)
	case "spoiler":
		v = new(RichTextSpoiler)
	case "date_time":
		v = new(RichTextDateTime)
	case "text_mention":
		v = new(RichTextTextMention)
	case "subscript":
		v = new(RichTextSubscript)
	case "superscript":
		v = new(RichTextSuperscript)
	case "marked":
		v = new(RichTextMarked)
	case "code":
		v = new(RichTextCode)
	case "custom_emoji":
		v = new(RichTextCustomEmoji)
	case "mathematical_expression":
		v = new(RichTextMathematicalExpression)
	case "url":
		v = new(RichTextUrl)
	case "email_address":
		v = new(RichTextEmailAddress)
	case "phone_number":
		v = new(RichTextPhoneNumber)
	case "bank_card_number":
		v = new(RichTextBankCardNumber)
	case "mention":
		v = new(RichTextMention)
	case "hashtag":
		v = new(RichTextHashtag)
	case "cashtag":
		v = new(RichTextCashtag)
	case "bot_command":
		v = new(RichTextBotCommand)
	case "button":
		v = new(RichTextButton)
	case "anchor":
		v = new(RichTextAnchor)
	case "anchor_link":
		v = new(RichTextAnchorLink)
	case "reference":
		v = new(RichTextReference)
	case "reference_link":
		v = new(RichTextReferenceLink)
	default:
		return newUnknown(head.Kind, data), nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return nil, err
	}
	return v, nil
}

// A bold text.
type RichTextBold struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "bold".
func (v RichTextBold) MarshalJSON() ([]byte, error) {
	type fields RichTextBold
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"bold", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextBold) UnmarshalJSON(data []byte) error {
	type fields RichTextBold
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// An italicized text.
type RichTextItalic struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "italic".
func (v RichTextItalic) MarshalJSON() ([]byte, error) {
	type fields RichTextItalic
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"italic", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextItalic) UnmarshalJSON(data []byte) error {
	type fields RichTextItalic
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// An underlined text.
type RichTextUnderline struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "underline".
func (v RichTextUnderline) MarshalJSON() ([]byte, error) {
	type fields RichTextUnderline
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"underline", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextUnderline) UnmarshalJSON(data []byte) error {
	type fields RichTextUnderline
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A strikethrough text.
type RichTextStrikethrough struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "strikethrough".
func (v RichTextStrikethrough) MarshalJSON() ([]byte, error) {
	type fields RichTextStrikethrough
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"strikethrough", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextStrikethrough) UnmarshalJSON(data []byte) error {
	type fields RichTextStrikethrough
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A text covered by a spoiler.
type RichTextSpoiler struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "spoiler".
func (v RichTextSpoiler) MarshalJSON() ([]byte, error) {
	type fields RichTextSpoiler
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"spoiler", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextSpoiler) UnmarshalJSON(data []byte) error {
	type fields RichTextSpoiler
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// Formatted date and time.
type RichTextDateTime struct {
	// The text
	Text RichText `json:"text"`
	// The Unix time associated with the entity
	UnixTime int64 `json:"unix_time"`
	// The string that defines the formatting of the date and time.
	DateTimeFormat string `json:"date_time_format"`
}

// MarshalJSON encodes v with "type" set to "date_time".
func (v RichTextDateTime) MarshalJSON() ([]byte, error) {
	type fields RichTextDateTime
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"date_time", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextDateTime) UnmarshalJSON(data []byte) error {
	type fields RichTextDateTime
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A mention of a Telegram user by their identifier.
type RichTextTextMention struct {
	// The text
	Text RichText `json:"text"`
	// The mentioned user
	User User `json:"user"`
}

// MarshalJSON encodes v with "type" set to "text_mention".
func (v RichTextTextMention) MarshalJSON() ([]byte, error) {
	type fields RichTextTextMention
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"text_mention", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextTextMention) UnmarshalJSON(data []byte) error {
	type fields RichTextTextMention
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A subscript text.
type RichTextSubscript struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "subscript".
func (v RichTextSubscript) MarshalJSON() ([]byte, error) {
	type fields RichTextSubscript
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"subscript", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextSubscript) UnmarshalJSON(data []byte) error {
	type fields RichTextSubscript
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A superscript text.
type RichTextSuperscript struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "superscript".
func (v RichTextSuperscript) MarshalJSON() ([]byte, error) {
	type fields RichTextSuperscript
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"superscript", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextSuperscript) UnmarshalJSON(data []byte) error {
	type fields RichTextSuperscript
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A marked text.
type RichTextMarked struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "marked".
func (v RichTextMarked) MarshalJSON() ([]byte, error) {
	type fields RichTextMarked
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"marked", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextMarked) UnmarshalJSON(data []byte) error {
	type fields RichTextMarked
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A monowidth text.
type RichTextCode struct {
	// The text
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "code".
func (v RichTextCode) MarshalJSON() ([]byte, error) {
	type fields RichTextCode
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"code", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextCode) UnmarshalJSON(data []byte) error {
	type fields RichTextCode
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A custom emoji.
type RichTextCustomEmoji struct {
	// Unique identifier of the custom emoji.
	CustomEmojiID string `json:"custom_emoji_id"`
	// Alternative emoji for the custom emoji
	AlternativeText string `json:"alternative_text"`
}

// MarshalJSON encodes v with "type" set to "custom_emoji".
func (v RichTextCustomEmoji) MarshalJSON() ([]byte, error) {
	type fields RichTextCustomEmoji
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"custom_emoji", fields(v)})
}

// A mathematical expression.
type RichTextMathematicalExpression struct {
	// The expression in LaTeX format
	Expression string `json:"expression"`
}

// MarshalJSON encodes v with "type" set to "mathematical_expression".
func (v RichTextMathematicalExpression) MarshalJSON() ([]byte, error) {
	type fields RichTextMathematicalExpression
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mathematical_expression", fields(v)})
}

// A text with a link.
type RichTextUrl struct {
	// The text
	Text RichText `json:"text"`
	// URL of the link
	URL string `json:"url"`
}

// MarshalJSON encodes v with "type" set to "url".
func (v RichTextUrl) MarshalJSON() ([]byte, error) {
	type fields RichTextUrl
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"url", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextUrl) UnmarshalJSON(data []byte) error {
	type fields RichTextUrl
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A text with an email address.
type RichTextEmailAddress struct {
	// The text
	Text RichText `json:"text"`
	// The email address
	EmailAddress string `json:"email_address"`
}

// MarshalJSON encodes v with "type" set to "email_address".
func (v RichTextEmailAddress) MarshalJSON() ([]byte, error) {
	type fields RichTextEmailAddress
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"email_address", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextEmailAddress) UnmarshalJSON(data []byte) error {
	type fields RichTextEmailAddress
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A text with a phone number.
type RichTextPhoneNumber struct {
	// The text
	Text RichText `json:"text"`
	// The phone number
	PhoneNumber string `json:"phone_number"`
}

// MarshalJSON encodes v with "type" set to "phone_number".
func (v RichTextPhoneNumber) MarshalJSON() ([]byte, error) {
	type fields RichTextPhoneNumber
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"phone_number", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextPhoneNumber) UnmarshalJSON(data []byte) error {
	type fields RichTextPhoneNumber
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A text with a bank card number.
type RichTextBankCardNumber struct {
	// The text
	Text RichText `json:"text"`
	// The bank card number
	BankCardNumber string `json:"bank_card_number"`
}

// MarshalJSON encodes v with "type" set to "bank_card_number".
func (v RichTextBankCardNumber) MarshalJSON() ([]byte, error) {
	type fields RichTextBankCardNumber
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"bank_card_number", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextBankCardNumber) UnmarshalJSON(data []byte) error {
	type fields RichTextBankCardNumber
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A mention by a username.
type RichTextMention struct {
	// The text
	Text RichText `json:"text"`
	// The username
	Username string `json:"username"`
}

// MarshalJSON encodes v with "type" set to "mention".
func (v RichTextMention) MarshalJSON() ([]byte, error) {
	type fields RichTextMention
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mention", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextMention) UnmarshalJSON(data []byte) error {
	type fields RichTextMention
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A hashtag.
type RichTextHashtag struct {
	// The text
	Text RichText `json:"text"`
	// The hashtag
	Hashtag string `json:"hashtag"`
}

// MarshalJSON encodes v with "type" set to "hashtag".
func (v RichTextHashtag) MarshalJSON() ([]byte, error) {
	type fields RichTextHashtag
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"hashtag", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextHashtag) UnmarshalJSON(data []byte) error {
	type fields RichTextHashtag
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A cashtag.
type RichTextCashtag struct {
	// The text
	Text RichText `json:"text"`
	// The cashtag
	Cashtag string `json:"cashtag"`
}

// MarshalJSON encodes v with "type" set to "cashtag".
func (v RichTextCashtag) MarshalJSON() ([]byte, error) {
	type fields RichTextCashtag
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"cashtag", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextCashtag) UnmarshalJSON(data []byte) error {
	type fields RichTextCashtag
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A bot command.
type RichTextBotCommand struct {
	// The text
	Text RichText `json:"text"`
	// The bot command
	BotCommand string `json:"bot_command"`
}

// MarshalJSON encodes v with "type" set to "bot_command".
func (v RichTextBotCommand) MarshalJSON() ([]byte, error) {
	type fields RichTextBotCommand
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"bot_command", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextBotCommand) UnmarshalJSON(data []byte) error {
	type fields RichTextBotCommand
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A button.
type RichTextButton struct {
	// The button
	Button RichMessageButton `json:"button"`
}

// MarshalJSON encodes v with "type" set to "button".
func (v RichTextButton) MarshalJSON() ([]byte, error) {
	type fields RichTextButton
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"button", fields(v)})
}

// An anchor.
type RichTextAnchor struct {
	// The name of the anchor
	Name string `json:"name"`
}

// MarshalJSON encodes v with "type" set to "anchor".
func (v RichTextAnchor) MarshalJSON() ([]byte, error) {
	type fields RichTextAnchor
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"anchor", fields(v)})
}

// A link to an anchor.
type RichTextAnchorLink struct {
	// The link text
	Text RichText `json:"text"`
	// The name of the anchor.
	AnchorName string `json:"anchor_name"`
}

// MarshalJSON encodes v with "type" set to "anchor_link".
func (v RichTextAnchorLink) MarshalJSON() ([]byte, error) {
	type fields RichTextAnchorLink
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"anchor_link", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextAnchorLink) UnmarshalJSON(data []byte) error {
	type fields RichTextAnchorLink
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A reference.
type RichTextReference struct {
	// Text of the reference
	Text RichText `json:"text"`
	// The name of the reference
	Name string `json:"name"`
}

// MarshalJSON encodes v with "type" set to "reference".
func (v RichTextReference) MarshalJSON() ([]byte, error) {
	type fields RichTextReference
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"reference", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextReference) UnmarshalJSON(data []byte) error {
	type fields RichTextReference
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A link to a reference.
type RichTextReferenceLink struct {
	// The link text
	Text RichText `json:"text"`
	// The name of the reference
	ReferenceName string `json:"reference_name"`
}

// MarshalJSON encodes v with "type" set to "reference_link".
func (v RichTextReferenceLink) MarshalJSON() ([]byte, error) {
	type fields RichTextReferenceLink
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"reference_link", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichTextReferenceLink) UnmarshalJSON(data []byte) error {
	type fields RichTextReferenceLink
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// Caption of a rich formatted block.
type RichBlockCaption struct {
	// Block caption
	Text RichText `json:"text"`
	// Block credit which corresponds to the HTML tag <cite>
	Credit RichText `json:"credit,omitempty"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockCaption) UnmarshalJSON(data []byte) error {
	type fields RichBlockCaption
	var raw struct {
		*fields
		Text   json.RawMessage `json:"text"`
		Credit json.RawMessage `json:"credit"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	if v.Credit, err = decodeRichText(raw.Credit); err != nil {
		return err
	}
	return nil
}

// Cell in a table.
type RichBlockTableCell struct {
	// Text in the cell.
	Text RichText `json:"text,omitempty"`
	// True, if the cell is a header cell
	IsHeader bool `json:"is_header,omitempty"`
	// The number of columns the cell spans if it is bigger than 1
	Colspan *int `json:"colspan,omitempty"`
	// The number of rows the cell spans if it is bigger than 1
	Rowspan *int `json:"rowspan,omitempty"`
	// Horizontal cell content alignment.
	Align string `json:"align"`
	// Vertical cell content alignment.
	Valign string `json:"valign"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockTableCell) UnmarshalJSON(data []byte) error {
	type fields RichBlockTableCell
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// An item of a list.
type RichBlockListItem struct {
	// Label of the item
	Label string `json:"label"`
	// The content of the item
	Blocks []RichBlock `json:"blocks"`
	// True, if the item has a checkbox
	HasCheckbox bool `json:"has_checkbox,omitempty"`
	// True, if the item has a checked checkbox
	IsChecked bool `json:"is_checked,omitempty"`
	// For ordered lists, the numeric value of the item label
	Value *int `json:"value,omitempty"`
	// For ordered lists, the type of the item label; must be one of “a” for lowercase letters,
	// “A” for uppercase letters, “i” for lowercase Roman numerals, “I” for uppercase Roman
	// numerals, or “1” for decimal numbers
	Type *string `json:"type,omitempty"`
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockListItem) UnmarshalJSON(data []byte) error {
	type fields RichBlockListItem
	var raw struct {
		*fields
		Blocks []json.RawMessage `json:"blocks"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	return nil
}

// RichBlock represents a block in a rich formatted message.
//
// Implemented by *RichBlockParagraph, *RichBlockSectionHeading, *RichBlockPreformatted,
// *RichBlockFooter, *RichBlockDivider, *RichBlockMathematicalExpression, *RichBlockAnchor,
// *RichBlockList, *RichBlockBlockQuotation, *RichBlockExpandableBlockQuotation,
// *RichBlockPullQuotation, *RichBlockCollage, *RichBlockSlideshow, *RichBlockTable,
// *RichBlockDetails, *RichBlockMap, *RichBlockButtons, *RichBlockAnimation, *RichBlockAudio,
// *RichBlockDocument, *RichBlockPhoto, *RichBlockVideo, *RichBlockVoiceNote, *RichBlockThinking and
// *Unknown.
type RichBlock interface{ richBlock() }

func (*RichBlockParagraph) richBlock()                {}
func (*RichBlockSectionHeading) richBlock()           {}
func (*RichBlockPreformatted) richBlock()             {}
func (*RichBlockFooter) richBlock()                   {}
func (*RichBlockDivider) richBlock()                  {}
func (*RichBlockMathematicalExpression) richBlock()   {}
func (*RichBlockAnchor) richBlock()                   {}
func (*RichBlockList) richBlock()                     {}
func (*RichBlockBlockQuotation) richBlock()           {}
func (*RichBlockExpandableBlockQuotation) richBlock() {}
func (*RichBlockPullQuotation) richBlock()            {}
func (*RichBlockCollage) richBlock()                  {}
func (*RichBlockSlideshow) richBlock()                {}
func (*RichBlockTable) richBlock()                    {}
func (*RichBlockDetails) richBlock()                  {}
func (*RichBlockMap) richBlock()                      {}
func (*RichBlockButtons) richBlock()                  {}
func (*RichBlockAnimation) richBlock()                {}
func (*RichBlockAudio) richBlock()                    {}
func (*RichBlockDocument) richBlock()                 {}
func (*RichBlockPhoto) richBlock()                    {}
func (*RichBlockVideo) richBlock()                    {}
func (*RichBlockVoiceNote) richBlock()                {}
func (*RichBlockThinking) richBlock()                 {}
func (*Unknown) richBlock()                           {}

func decodeRichBlock(data []byte) (RichBlock, error) {
	if isNull(data) {
		return nil, nil
	}
	var head struct {
		Kind string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	var v RichBlock
	switch head.Kind {
	case "paragraph":
		v = new(RichBlockParagraph)
	case "heading":
		v = new(RichBlockSectionHeading)
	case "pre":
		v = new(RichBlockPreformatted)
	case "footer":
		v = new(RichBlockFooter)
	case "divider":
		v = new(RichBlockDivider)
	case "mathematical_expression":
		v = new(RichBlockMathematicalExpression)
	case "anchor":
		v = new(RichBlockAnchor)
	case "list":
		v = new(RichBlockList)
	case "blockquote":
		v = new(RichBlockBlockQuotation)
	case "expandable_blockquote":
		v = new(RichBlockExpandableBlockQuotation)
	case "pullquote":
		v = new(RichBlockPullQuotation)
	case "collage":
		v = new(RichBlockCollage)
	case "slideshow":
		v = new(RichBlockSlideshow)
	case "table":
		v = new(RichBlockTable)
	case "details":
		v = new(RichBlockDetails)
	case "map":
		v = new(RichBlockMap)
	case "buttons":
		v = new(RichBlockButtons)
	case "animation":
		v = new(RichBlockAnimation)
	case "audio":
		v = new(RichBlockAudio)
	case "document":
		v = new(RichBlockDocument)
	case "photo":
		v = new(RichBlockPhoto)
	case "video":
		v = new(RichBlockVideo)
	case "voice_note":
		v = new(RichBlockVoiceNote)
	case "thinking":
		v = new(RichBlockThinking)
	default:
		return newUnknown(head.Kind, data), nil
	}
	if err := json.Unmarshal(data, v); err != nil {
		return nil, err
	}
	return v, nil
}

// A text paragraph, corresponding to the HTML tag <p>.
type RichBlockParagraph struct {
	// Text of the block
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "paragraph".
func (v RichBlockParagraph) MarshalJSON() ([]byte, error) {
	type fields RichBlockParagraph
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"paragraph", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockParagraph) UnmarshalJSON(data []byte) error {
	type fields RichBlockParagraph
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A section heading, corresponding to the HTML tags <h1>, <h2>, <h3>, <h4>, <h5>, or <h6>.
type RichBlockSectionHeading struct {
	// Text of the block
	Text RichText `json:"text"`
	// Relative size of the text font; 1-6, 1 is the largest, 6 is the smallest
	Size int `json:"size"`
}

// MarshalJSON encodes v with "type" set to "heading".
func (v RichBlockSectionHeading) MarshalJSON() ([]byte, error) {
	type fields RichBlockSectionHeading
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"heading", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockSectionHeading) UnmarshalJSON(data []byte) error {
	type fields RichBlockSectionHeading
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A preformatted text block, corresponding to the nested HTML tags <pre> and <code>.
type RichBlockPreformatted struct {
	// Text of the block
	Text RichText `json:"text"`
	// The programming language of the text
	Language *string `json:"language,omitempty"`
}

// MarshalJSON encodes v with "type" set to "pre".
func (v RichBlockPreformatted) MarshalJSON() ([]byte, error) {
	type fields RichBlockPreformatted
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"pre", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockPreformatted) UnmarshalJSON(data []byte) error {
	type fields RichBlockPreformatted
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A footer, corresponding to the HTML tag <footer>.
type RichBlockFooter struct {
	// Text of the block
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "footer".
func (v RichBlockFooter) MarshalJSON() ([]byte, error) {
	type fields RichBlockFooter
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"footer", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockFooter) UnmarshalJSON(data []byte) error {
	type fields RichBlockFooter
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// A divider, corresponding to the HTML tag <hr/>.
type RichBlockDivider struct{}

// MarshalJSON encodes v with "type" set to "divider".
func (v RichBlockDivider) MarshalJSON() ([]byte, error) {
	type fields RichBlockDivider
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"divider", fields(v)})
}

// A block with a mathematical expression in LaTeX format, corresponding to the custom HTML tag
// <tg-math-block>.
type RichBlockMathematicalExpression struct {
	// The mathematical expression in LaTeX format
	Expression string `json:"expression"`
}

// MarshalJSON encodes v with "type" set to "mathematical_expression".
func (v RichBlockMathematicalExpression) MarshalJSON() ([]byte, error) {
	type fields RichBlockMathematicalExpression
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mathematical_expression", fields(v)})
}

// A block with an anchor, corresponding to the HTML tag <a> with the attribute name.
type RichBlockAnchor struct {
	// The name of the anchor
	Name string `json:"name"`
}

// MarshalJSON encodes v with "type" set to "anchor".
func (v RichBlockAnchor) MarshalJSON() ([]byte, error) {
	type fields RichBlockAnchor
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"anchor", fields(v)})
}

// A list of blocks, corresponding to the HTML tag <ul> or <ol> with multiple nested tags <li>.
type RichBlockList struct {
	// Items of the list
	Items []RichBlockListItem `json:"items"`
}

// MarshalJSON encodes v with "type" set to "list".
func (v RichBlockList) MarshalJSON() ([]byte, error) {
	type fields RichBlockList
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"list", fields(v)})
}

// A block quotation, corresponding to the HTML tag <blockquote>.
type RichBlockBlockQuotation struct {
	// Content of the block
	Blocks []RichBlock `json:"blocks"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "blockquote".
func (v RichBlockBlockQuotation) MarshalJSON() ([]byte, error) {
	type fields RichBlockBlockQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"blockquote", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockBlockQuotation) UnmarshalJSON(data []byte) error {
	type fields RichBlockBlockQuotation
	var raw struct {
		*fields
		Blocks []json.RawMessage `json:"blocks"`
		Credit json.RawMessage   `json:"credit"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	if v.Credit, err = decodeRichText(raw.Credit); err != nil {
		return err
	}
	return nil
}

// A block quotation, corresponding to the HTML tag <blockquote> with custom attribute "expandable".
type RichBlockExpandableBlockQuotation struct {
	// Content of the block
	Text RichText `json:"text"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "expandable_blockquote".
func (v RichBlockExpandableBlockQuotation) MarshalJSON() ([]byte, error) {
	type fields RichBlockExpandableBlockQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"expandable_blockquote", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockExpandableBlockQuotation) UnmarshalJSON(data []byte) error {
	type fields RichBlockExpandableBlockQuotation
	var raw struct {
		*fields
		Text   json.RawMessage `json:"text"`
		Credit json.RawMessage `json:"credit"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	if v.Credit, err = decodeRichText(raw.Credit); err != nil {
		return err
	}
	return nil
}

// A quotation with centered text, loosely corresponding to the HTML tag <aside>.
type RichBlockPullQuotation struct {
	// Text of the block
	Text RichText `json:"text"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "pullquote".
func (v RichBlockPullQuotation) MarshalJSON() ([]byte, error) {
	type fields RichBlockPullQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"pullquote", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockPullQuotation) UnmarshalJSON(data []byte) error {
	type fields RichBlockPullQuotation
	var raw struct {
		*fields
		Text   json.RawMessage `json:"text"`
		Credit json.RawMessage `json:"credit"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	if v.Credit, err = decodeRichText(raw.Credit); err != nil {
		return err
	}
	return nil
}

// A collage, corresponding to the custom HTML tag <tg-collage>.
type RichBlockCollage struct {
	// Elements of the collage
	Blocks []RichBlock `json:"blocks"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "collage".
func (v RichBlockCollage) MarshalJSON() ([]byte, error) {
	type fields RichBlockCollage
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"collage", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockCollage) UnmarshalJSON(data []byte) error {
	type fields RichBlockCollage
	var raw struct {
		*fields
		Blocks []json.RawMessage `json:"blocks"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	return nil
}

// A slideshow, corresponding to the custom HTML tag <tg-slideshow>.
type RichBlockSlideshow struct {
	// Elements of the slideshow
	Blocks []RichBlock `json:"blocks"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "slideshow".
func (v RichBlockSlideshow) MarshalJSON() ([]byte, error) {
	type fields RichBlockSlideshow
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"slideshow", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockSlideshow) UnmarshalJSON(data []byte) error {
	type fields RichBlockSlideshow
	var raw struct {
		*fields
		Blocks []json.RawMessage `json:"blocks"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	return nil
}

// A table, corresponding to the HTML tag <table>.
type RichBlockTable struct {
	// Cells of the table
	Cells [][]RichBlockTableCell `json:"cells"`
	// True, if the table has borders
	IsBordered bool `json:"is_bordered,omitempty"`
	// True, if the table is striped
	IsStriped bool `json:"is_striped,omitempty"`
	// True, if table cells have smaller indents
	IsCompact bool `json:"is_compact,omitempty"`
	// Caption of the table
	Caption RichText `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "table".
func (v RichBlockTable) MarshalJSON() ([]byte, error) {
	type fields RichBlockTable
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"table", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockTable) UnmarshalJSON(data []byte) error {
	type fields RichBlockTable
	var raw struct {
		*fields
		Caption json.RawMessage `json:"caption"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Caption, err = decodeRichText(raw.Caption); err != nil {
		return err
	}
	return nil
}

// An expandable block for details disclosure, corresponding to the HTML tag <details>.
type RichBlockDetails struct {
	// Always shown summary of the block
	Summary RichText `json:"summary"`
	// Content of the block
	Blocks []RichBlock `json:"blocks"`
	// True, if the content of the block is visible by default
	IsOpen bool `json:"is_open,omitempty"`
}

// MarshalJSON encodes v with "type" set to "details".
func (v RichBlockDetails) MarshalJSON() ([]byte, error) {
	type fields RichBlockDetails
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"details", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockDetails) UnmarshalJSON(data []byte) error {
	type fields RichBlockDetails
	var raw struct {
		*fields
		Summary json.RawMessage   `json:"summary"`
		Blocks  []json.RawMessage `json:"blocks"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Summary, err = decodeRichText(raw.Summary); err != nil {
		return err
	}
	if v.Blocks, err = decodeEach(raw.Blocks, decodeRichBlock); err != nil {
		return err
	}
	return nil
}

// A block with a map, corresponding to the custom HTML tag <tg-map>.
type RichBlockMap struct {
	// Location of the center of the map
	Location Location `json:"location"`
	// Map zoom level
	Zoom int `json:"zoom"`
	// Expected width of the map
	Width int `json:"width"`
	// Expected height of the map
	Height int `json:"height"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "map".
func (v RichBlockMap) MarshalJSON() ([]byte, error) {
	type fields RichBlockMap
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"map", fields(v)})
}

// A block containing a list of buttons that are shown in one row, corresponding to the custom HTML
// tag <tg-button-row>.
type RichBlockButtons struct {
	// The buttons
	Buttons []RichMessageButton `json:"buttons"`
	// Horizontal alignment of the buttons.
	Align *string `json:"align,omitempty"`
}

// MarshalJSON encodes v with "type" set to "buttons".
func (v RichBlockButtons) MarshalJSON() ([]byte, error) {
	type fields RichBlockButtons
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"buttons", fields(v)})
}

// A block with an animation, corresponding to the HTML tag <video>.
type RichBlockAnimation struct {
	// The animation
	Animation Animation `json:"animation"`
	// True, if the media preview is covered by a spoiler animation
	HasSpoiler bool `json:"has_spoiler,omitempty"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "animation".
func (v RichBlockAnimation) MarshalJSON() ([]byte, error) {
	type fields RichBlockAnimation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"animation", fields(v)})
}

// A block with a music file, corresponding to the HTML tag <audio>.
type RichBlockAudio struct {
	// The audio
	Audio Audio `json:"audio"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "audio".
func (v RichBlockAudio) MarshalJSON() ([]byte, error) {
	type fields RichBlockAudio
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"audio", fields(v)})
}

// A block with a general file, corresponding to the custom HTML tag <tg-document>.
type RichBlockDocument struct {
	// The document
	Document Document `json:"document"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "document".
func (v RichBlockDocument) MarshalJSON() ([]byte, error) {
	type fields RichBlockDocument
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"document", fields(v)})
}

// A block with a photo, corresponding to the HTML tag <img>.
type RichBlockPhoto struct {
	// Available sizes of the photo
	Photo []PhotoSize `json:"photo"`
	// True, if the media preview is covered by a spoiler animation
	HasSpoiler bool `json:"has_spoiler,omitempty"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "photo".
func (v RichBlockPhoto) MarshalJSON() ([]byte, error) {
	type fields RichBlockPhoto
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"photo", fields(v)})
}

// A block with a video, corresponding to the HTML tag <video>.
type RichBlockVideo struct {
	// The video
	Video Video `json:"video"`
	// True, if the media preview is covered by a spoiler animation
	HasSpoiler bool `json:"has_spoiler,omitempty"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "video".
func (v RichBlockVideo) MarshalJSON() ([]byte, error) {
	type fields RichBlockVideo
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"video", fields(v)})
}

// A block with a voice note, corresponding to the HTML tag <audio>.
type RichBlockVoiceNote struct {
	// The voice note
	VoiceNote Voice `json:"voice_note"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "voice_note".
func (v RichBlockVoiceNote) MarshalJSON() ([]byte, error) {
	type fields RichBlockVoiceNote
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"voice_note", fields(v)})
}

// A block with a “Thinking…” placeholder, corresponding to the custom HTML tag <tg-thinking>.
type RichBlockThinking struct {
	// Text of the block.
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "thinking".
func (v RichBlockThinking) MarshalJSON() ([]byte, error) {
	type fields RichBlockThinking
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"thinking", fields(v)})
}

// UnmarshalJSON decodes v, choosing the concrete type of each field that can hold several types.
func (v *RichBlockThinking) UnmarshalJSON(data []byte) error {
	type fields RichBlockThinking
	var raw struct {
		*fields
		Text json.RawMessage `json:"text"`
	}
	raw.fields = (*fields)(v)
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var err error
	if v.Text, err = decodeRichText(raw.Text); err != nil {
		return err
	}
	return nil
}

// An item of a list to be sent.
type InputRichBlockListItem struct {
	// The content of the item
	Blocks []InputRichBlock `json:"blocks"`
	// Pass True if the item has a checkbox
	HasCheckbox bool `json:"has_checkbox,omitempty"`
	// Pass True if the item has a checked checkbox
	IsChecked bool `json:"is_checked,omitempty"`
	// For ordered lists, the numeric value of the item label
	Value *int `json:"value,omitempty"`
	// For ordered lists, the type of the item label; must be one of “a” for lowercase letters,
	// “A” for uppercase letters, “i” for lowercase Roman numerals, “I” for uppercase Roman
	// numerals, or “1” for decimal numbers
	Type *string `json:"type,omitempty"`
}

// InputRichBlock represents a block in a rich formatted message to be sent.
//
// Implemented by *InputRichBlockParagraph, *InputRichBlockSectionHeading,
// *InputRichBlockPreformatted, *InputRichBlockFooter, *InputRichBlockDivider,
// *InputRichBlockMathematicalExpression, *InputRichBlockAnchor, *InputRichBlockList,
// *InputRichBlockBlockQuotation, *InputRichBlockExpandableBlockQuotation,
// *InputRichBlockPullQuotation, *InputRichBlockCollage, *InputRichBlockSlideshow,
// *InputRichBlockTable, *InputRichBlockDetails, *InputRichBlockMap, *InputRichBlockButtons,
// *InputRichBlockAnimation, *InputRichBlockAudio, *InputRichBlockDocument, *InputRichBlockPhoto,
// *InputRichBlockVideo, *InputRichBlockVoiceNote and *InputRichBlockThinking.
type InputRichBlock interface{ inputRichBlock() }

func (*InputRichBlockParagraph) inputRichBlock()                {}
func (*InputRichBlockSectionHeading) inputRichBlock()           {}
func (*InputRichBlockPreformatted) inputRichBlock()             {}
func (*InputRichBlockFooter) inputRichBlock()                   {}
func (*InputRichBlockDivider) inputRichBlock()                  {}
func (*InputRichBlockMathematicalExpression) inputRichBlock()   {}
func (*InputRichBlockAnchor) inputRichBlock()                   {}
func (*InputRichBlockList) inputRichBlock()                     {}
func (*InputRichBlockBlockQuotation) inputRichBlock()           {}
func (*InputRichBlockExpandableBlockQuotation) inputRichBlock() {}
func (*InputRichBlockPullQuotation) inputRichBlock()            {}
func (*InputRichBlockCollage) inputRichBlock()                  {}
func (*InputRichBlockSlideshow) inputRichBlock()                {}
func (*InputRichBlockTable) inputRichBlock()                    {}
func (*InputRichBlockDetails) inputRichBlock()                  {}
func (*InputRichBlockMap) inputRichBlock()                      {}
func (*InputRichBlockButtons) inputRichBlock()                  {}
func (*InputRichBlockAnimation) inputRichBlock()                {}
func (*InputRichBlockAudio) inputRichBlock()                    {}
func (*InputRichBlockDocument) inputRichBlock()                 {}
func (*InputRichBlockPhoto) inputRichBlock()                    {}
func (*InputRichBlockVideo) inputRichBlock()                    {}
func (*InputRichBlockVoiceNote) inputRichBlock()                {}
func (*InputRichBlockThinking) inputRichBlock()                 {}

// A text paragraph, corresponding to the HTML tag <p>.
type InputRichBlockParagraph struct {
	// Text of the block
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "paragraph".
func (v InputRichBlockParagraph) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockParagraph
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"paragraph", fields(v)})
}

// A section heading, corresponding to the HTML tags <h1>, <h2>, <h3>, <h4>, <h5>, or <h6>.
type InputRichBlockSectionHeading struct {
	// Text of the block
	Text RichText `json:"text"`
	// Relative size of the text font; 1-6, 1 is the largest, 6 is the smallest
	Size int `json:"size"`
}

// MarshalJSON encodes v with "type" set to "heading".
func (v InputRichBlockSectionHeading) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockSectionHeading
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"heading", fields(v)})
}

// A preformatted text block, corresponding to the nested HTML tags <pre> and <code>.
type InputRichBlockPreformatted struct {
	// Text of the block
	Text RichText `json:"text"`
	// The programming language of the text
	Language *string `json:"language,omitempty"`
}

// MarshalJSON encodes v with "type" set to "pre".
func (v InputRichBlockPreformatted) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockPreformatted
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"pre", fields(v)})
}

// A footer, corresponding to the HTML tag <footer>.
type InputRichBlockFooter struct {
	// Text of the block
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "footer".
func (v InputRichBlockFooter) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockFooter
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"footer", fields(v)})
}

// A divider, corresponding to the HTML tag <hr/>.
type InputRichBlockDivider struct{}

// MarshalJSON encodes v with "type" set to "divider".
func (v InputRichBlockDivider) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockDivider
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"divider", fields(v)})
}

// A block with a mathematical expression in LaTeX format, corresponding to the custom HTML tag
// <tg-math-block>.
type InputRichBlockMathematicalExpression struct {
	// The mathematical expression in LaTeX format
	Expression string `json:"expression"`
}

// MarshalJSON encodes v with "type" set to "mathematical_expression".
func (v InputRichBlockMathematicalExpression) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockMathematicalExpression
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"mathematical_expression", fields(v)})
}

// A block with an anchor, corresponding to the HTML tag <a> with the attribute name.
type InputRichBlockAnchor struct {
	// The name of the anchor
	Name string `json:"name"`
}

// MarshalJSON encodes v with "type" set to "anchor".
func (v InputRichBlockAnchor) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockAnchor
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"anchor", fields(v)})
}

// A list of blocks, corresponding to the HTML tag <ul> or <ol> with multiple nested tags <li>.
type InputRichBlockList struct {
	// Items of the list
	Items []InputRichBlockListItem `json:"items"`
}

// MarshalJSON encodes v with "type" set to "list".
func (v InputRichBlockList) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockList
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"list", fields(v)})
}

// A block quotation, corresponding to the HTML tag <blockquote>.
type InputRichBlockBlockQuotation struct {
	// Content of the block
	Blocks []InputRichBlock `json:"blocks"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "blockquote".
func (v InputRichBlockBlockQuotation) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockBlockQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"blockquote", fields(v)})
}

// A block quotation, corresponding to the HTML tag <blockquote> with custom attribute "expandable".
type InputRichBlockExpandableBlockQuotation struct {
	// Content of the block
	Text RichText `json:"text"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "expandable_blockquote".
func (v InputRichBlockExpandableBlockQuotation) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockExpandableBlockQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"expandable_blockquote", fields(v)})
}

// A quotation with centered text, loosely corresponding to the HTML tag <aside>.
type InputRichBlockPullQuotation struct {
	// Text of the block
	Text RichText `json:"text"`
	// Credit of the block
	Credit RichText `json:"credit,omitempty"`
}

// MarshalJSON encodes v with "type" set to "pullquote".
func (v InputRichBlockPullQuotation) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockPullQuotation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"pullquote", fields(v)})
}

// A collage, corresponding to the custom HTML tag <tg-collage>.
type InputRichBlockCollage struct {
	// Elements of the collage
	Blocks []InputRichBlock `json:"blocks"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "collage".
func (v InputRichBlockCollage) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockCollage
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"collage", fields(v)})
}

// A slideshow, corresponding to the custom HTML tag <tg-slideshow>.
type InputRichBlockSlideshow struct {
	// Elements of the slideshow
	Blocks []InputRichBlock `json:"blocks"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "slideshow".
func (v InputRichBlockSlideshow) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockSlideshow
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"slideshow", fields(v)})
}

// A table, corresponding to the HTML tag <table>.
type InputRichBlockTable struct {
	// Cells of the table
	Cells [][]RichBlockTableCell `json:"cells"`
	// Pass True if the table has borders
	IsBordered bool `json:"is_bordered,omitempty"`
	// Pass True if the table is striped
	IsStriped bool `json:"is_striped,omitempty"`
	// Pass True if table cells must have smaller indents
	IsCompact bool `json:"is_compact,omitempty"`
	// Caption of the table
	Caption RichText `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "table".
func (v InputRichBlockTable) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockTable
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"table", fields(v)})
}

// An expandable block for details disclosure, corresponding to the HTML tag <details>.
type InputRichBlockDetails struct {
	// Always shown summary of the block
	Summary RichText `json:"summary"`
	// Content of the block
	Blocks []InputRichBlock `json:"blocks"`
	// Pass True if the content of the block is visible by default
	IsOpen bool `json:"is_open,omitempty"`
}

// MarshalJSON encodes v with "type" set to "details".
func (v InputRichBlockDetails) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockDetails
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"details", fields(v)})
}

// A block with a map, corresponding to the custom HTML tag <tg-map>.
type InputRichBlockMap struct {
	// Location of the center of the map
	Location Location `json:"location"`
	// Map zoom level; 0-24
	Zoom *int `json:"zoom,omitempty"`
	// Map width; 0-10000
	Width *int `json:"width,omitempty"`
	// Map height; 0-10000
	Height *int `json:"height,omitempty"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "map".
func (v InputRichBlockMap) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockMap
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"map", fields(v)})
}

// A block containing a list of buttons that are shown in one row, corresponding to the custom HTML
// tag <tg-button-row>.
type InputRichBlockButtons struct {
	// List of 1-8 buttons to send
	Buttons []RichMessageButton `json:"buttons"`
	// Horizontal alignment of the buttons.
	Align *string `json:"align,omitempty"`
}

// MarshalJSON encodes v with "type" set to "buttons".
func (v InputRichBlockButtons) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockButtons
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"buttons", fields(v)})
}

// A block with an animation, corresponding to the HTML tag <video>.
type InputRichBlockAnimation struct {
	// The animation.
	Animation InputMediaAnimation `json:"animation"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "animation".
func (v InputRichBlockAnimation) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockAnimation
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"animation", fields(v)})
}

// A block with a music file, corresponding to the HTML tag <audio>.
type InputRichBlockAudio struct {
	// The audio.
	Audio InputMediaAudio `json:"audio"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "audio".
func (v InputRichBlockAudio) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockAudio
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"audio", fields(v)})
}

// A block with a general file, corresponding to the custom HTML tag <tg-document>.
type InputRichBlockDocument struct {
	// The document.
	Document InputMediaDocument `json:"document"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "document".
func (v InputRichBlockDocument) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockDocument
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"document", fields(v)})
}

// A block with a photo, corresponding to the HTML tag <img>.
type InputRichBlockPhoto struct {
	// The photo.
	Photo InputMediaPhoto `json:"photo"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "photo".
func (v InputRichBlockPhoto) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockPhoto
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"photo", fields(v)})
}

// A block with a video, corresponding to the HTML tag <video>.
type InputRichBlockVideo struct {
	// The video.
	Video InputMediaVideo `json:"video"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "video".
func (v InputRichBlockVideo) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockVideo
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"video", fields(v)})
}

// A block with a voice note, corresponding to the HTML tag <audio>.
type InputRichBlockVoiceNote struct {
	// The voice note.
	VoiceNote InputMediaVoiceNote `json:"voice_note"`
	// Caption of the block
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// MarshalJSON encodes v with "type" set to "voice_note".
func (v InputRichBlockVoiceNote) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockVoiceNote
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"voice_note", fields(v)})
}

// A block with a “Thinking…” placeholder, corresponding to the custom HTML tag <tg-thinking>.
type InputRichBlockThinking struct {
	// Text of the block.
	Text RichText `json:"text"`
}

// MarshalJSON encodes v with "type" set to "thinking".
func (v InputRichBlockThinking) MarshalJSON() ([]byte, error) {
	type fields InputRichBlockThinking
	return json.Marshal(struct {
		Type string `json:"type"`
		fields
	}{"thinking", fields(v)})
}
