// Code generated by teleiq-gen. DO NOT EDIT.

package models

// Sticker represents a sticker.
type Sticker struct {
	// Identifier for this file, which can be used to download or reuse the file
	FileID string `json:"file_id"`
	// Unique identifier for this file, which is supposed to be the same over time and for different
	// bots.
	FileUniqueID string `json:"file_unique_id"`
	// Type of the sticker, currently one of “regular”, “mask”, “custom_emoji”.
	Type string `json:"type"`
	// Sticker width
	Width int `json:"width"`
	// Sticker height
	Height int `json:"height"`
	// True, if the sticker is animated
	IsAnimated bool `json:"is_animated"`
	// True, if the sticker is a video sticker
	IsVideo bool `json:"is_video"`
	// Sticker thumbnail in the .WEBP or .JPG format
	Thumbnail *PhotoSize `json:"thumbnail,omitempty"`
	// Emoji associated with the sticker
	Emoji *string `json:"emoji,omitempty"`
	// Name of the sticker set to which the sticker belongs
	SetName *string `json:"set_name,omitempty"`
	// For premium regular stickers, premium animation for the sticker
	PremiumAnimation *File `json:"premium_animation,omitempty"`
	// For mask stickers, the position where the mask should be placed
	MaskPosition *MaskPosition `json:"mask_position,omitempty"`
	// For custom emoji stickers, unique identifier of the custom emoji
	CustomEmojiID *string `json:"custom_emoji_id,omitempty"`
	// True, if the sticker must be repainted to a text color in messages, the color of the Telegram
	// Premium badge in emoji status, white color on chat photos, or another appropriate color in other
	// places
	NeedsRepainting bool `json:"needs_repainting,omitempty"`
	// File size in bytes
	FileSize *int64 `json:"file_size,omitempty"`
}

// StickerSet represents a sticker set.
type StickerSet struct {
	// Sticker set name
	Name string `json:"name"`
	// Sticker set title
	Title string `json:"title"`
	// Type of stickers in the set, currently one of “regular”, “mask”, “custom_emoji”
	StickerType string `json:"sticker_type"`
	// List of all set stickers
	Stickers []Sticker `json:"stickers"`
	// Sticker set thumbnail in the .WEBP, .TGS, or .WEBM format
	Thumbnail *PhotoSize `json:"thumbnail,omitempty"`
}

// MaskPosition describes the position on faces where a mask should be placed by default.
type MaskPosition struct {
	// The part of the face relative to which the mask should be placed.
	Point string `json:"point"`
	// Shift by X-axis measured in widths of the mask scaled to the face size, from left to right.
	XShift float64 `json:"x_shift"`
	// Shift by Y-axis measured in heights of the mask scaled to the face size, from top to bottom.
	YShift float64 `json:"y_shift"`
	// Mask scaling coefficient.
	Scale float64 `json:"scale"`
}

// InputSticker describes a sticker to be added to a sticker set.
type InputSticker struct {
	// The added sticker.
	Sticker InputFile `json:"sticker"`
	// Format of the added sticker, must be one of “static” for a .WEBP or .PNG image,
	// “animated” for a .TGS animation, “video” for a .WEBM video
	Format string `json:"format"`
	// List of 1-20 emoji associated with the sticker
	EmojiList []string `json:"emoji_list"`
	// Position where the mask should be placed on faces.
	MaskPosition *MaskPosition `json:"mask_position,omitempty"`
	// List of 0-20 search keywords for the sticker with total length of up to 64 characters.
	Keywords []string `json:"keywords,omitzero"`
}
