// Code generated by teleiq-gen. DO NOT EDIT.

package models

// Update represents an incoming update.
type Update struct {
	// The update's unique identifier.
	UpdateID int64 `json:"update_id"`
	// New incoming message of any kind - text, photo, sticker, etc.
	Message *Message `json:"message,omitempty"`
	// New version of a message that is known to the bot and was edited.
	EditedMessage *Message `json:"edited_message,omitempty"`
	// New incoming channel post of any kind - text, photo, sticker, etc.
	ChannelPost *Message `json:"channel_post,omitempty"`
	// New version of a channel post that is known to the bot and was edited.
	EditedChannelPost *Message `json:"edited_channel_post,omitempty"`
	// The bot was connected to or disconnected from a business account, or a user edited an existing
	// connection with the bot
	BusinessConnection *BusinessConnection `json:"business_connection,omitempty"`
	// New message from a connected business account
	BusinessMessage *Message `json:"business_message,omitempty"`
	// New version of a message from a connected business account
	EditedBusinessMessage *Message `json:"edited_business_message,omitempty"`
	// Messages were deleted from a connected business account
	DeletedBusinessMessages *BusinessMessagesDeleted `json:"deleted_business_messages,omitempty"`
	// New guest message.
	GuestMessage *Message `json:"guest_message,omitempty"`
	// A reaction to a message was changed by a user.
	MessageReaction *MessageReactionUpdated `json:"message_reaction,omitempty"`
	// Reactions to a message with anonymous reactions were changed.
	MessageReactionCount *MessageReactionCountUpdated `json:"message_reaction_count,omitempty"`
	// New incoming inline query
	InlineQuery *InlineQuery `json:"inline_query,omitempty"`
	// The result of an inline query that was chosen by a user and sent to their chat partner.
	ChosenInlineResult *ChosenInlineResult `json:"chosen_inline_result,omitempty"`
	// New incoming callback query
	CallbackQuery *CallbackQuery `json:"callback_query,omitempty"`
	// New incoming shipping query.
	ShippingQuery *ShippingQuery `json:"shipping_query,omitempty"`
	// New incoming pre-checkout query.
	PreCheckoutQuery *PreCheckoutQuery `json:"pre_checkout_query,omitempty"`
	// A user purchased paid media with a non-empty payload sent by the bot in a non-channel chat
	PurchasedPaidMedia *PaidMediaPurchased `json:"purchased_paid_media,omitempty"`
	// New poll state.
	Poll *Poll `json:"poll,omitempty"`
	// A user changed their answer in a non-anonymous poll.
	PollAnswer *PollAnswer `json:"poll_answer,omitempty"`
	// The bot's chat member status was updated in a chat.
	MyChatMember *ChatMemberUpdated `json:"my_chat_member,omitempty"`
	// A chat member's status was updated in a chat.
	ChatMember *ChatMemberUpdated `json:"chat_member,omitempty"`
	// A request to join the chat has been sent.
	ChatJoinRequest *ChatJoinRequest `json:"chat_join_request,omitempty"`
	// A chat boost was added or changed.
	ChatBoost *ChatBoostUpdated `json:"chat_boost,omitempty"`
	// A boost was removed from a chat.
	RemovedChatBoost *ChatBoostRemoved `json:"removed_chat_boost,omitempty"`
	// A new bot was created to be managed by the bot, or token or owner of a managed bot was changed
	ManagedBot *ManagedBotUpdated `json:"managed_bot,omitempty"`
	// User payment subscription has changed
	Subscription *BotSubscriptionUpdated `json:"subscription,omitempty"`
	// A user asked the bot to stop the generation of a message
	StoppedMessageGeneration *MessageGenerationStopped `json:"stopped_message_generation,omitempty"`
}

// Describes the current status of a webhook.
type WebhookInfo struct {
	// Webhook URL, may be empty if webhook is not set up
	URL string `json:"url"`
	// True, if a custom certificate was provided for webhook certificate checks
	HasCustomCertificate bool `json:"has_custom_certificate"`
	// Number of updates awaiting delivery
	PendingUpdateCount int `json:"pending_update_count"`
	// Currently used webhook IP address
	IPAddress *string `json:"ip_address,omitempty"`
	// Unix time for the most recent error that happened when trying to deliver an update via webhook
	LastErrorDate *int64 `json:"last_error_date,omitempty"`
	// Error message in human-readable format for the most recent error that happened when trying to
	// deliver an update via webhook
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// Unix time of the most recent error that happened when trying to synchronize available updates
	// with Telegram datacenters
	LastSynchronizationErrorDate *int64 `json:"last_synchronization_error_date,omitempty"`
	// The maximum allowed number of simultaneous HTTPS connections to the webhook for update delivery
	MaxConnections *int `json:"max_connections,omitempty"`
	// A list of update types the bot is subscribed to.
	AllowedUpdates []string `json:"allowed_updates,omitzero"`
}
